### ISSUE TITLE
Smudgeplot interpretation

### ISSUE THREAD

**Issue by fabianomenegidio** [KamilSJaron/smudgeplot#101]
I have troubles understanding my smudgeplot for two different genomes. I have used follwing commands to generate it

```
jellyfish count -C -m 21 -s 1000000000 -t 8 *.fastq -o kmer_counts.jf 
jellyfish histo kmer_counts.jf > kmer_k21.hist
L=$(smudgeplot.py cutoff kmer_k21.hist L)
U=$(smudgeplot.py cutoff kmer_k21.hist U)
echo $L $U
(30 2900)
jellyfish dump -c -L $L -U $U kmer_counts.jf | smudgeplot.py hetkmers -o kmer_pairs
smudgeplot.py plot kmer_pairs_coverages.tsv -o output

```

and it look like this:

Sali - cytometry: haploide

![salis_smudgeplot](https://user-images.githubusercontent.com/8346806/168406481-a52ec828-3fa8-4c28-bc7a-cc27b23365f5.png)
![salis_smudgeplot_log10](https://user-images.githubusercontent.com/8346806/168406484-0633ee67-190b-4868-bd0f-039ac8b5ce1f.png)

![download (2)](https://user-images.githubusercontent.com/8346806/168411478-d19f70c6-4570-48c1-8d4f-f7b62c9a6366.png)
![download](https://user-images.githubusercontent.com/8346806/168411480-4ba8c267-94b8-49a9-bcc4-0a066968bc50.png)
![download (3)](https://user-images.githubusercontent.com/8346806/168411477-d1e8c5e2-1ff7-4524-8a02-cf78b4a8f8e9.png)
![download (1)](https://user-images.githubusercontent.com/8346806/168411479-9076d027-e44b-44f0-b92e-8c381156b503.png)

GenomeScope apparently demonstrates a first peak near 30-50x. So, I used L=15. Below the Smudgeplot with L=15.

![sali_L15_smudgeplot](https://user-images.githubusercontent.com/8346806/168411676-ba20b598-6295-45a7-8410-262a3345ea2e.png)
![sali_L15_smudgeplot_log10](https://user-images.githubusercontent.com/8346806/168411677-972b930a-5302-4fce-969f-f1dbcbb5494a.png)

How should I understand my smudgeplot? Apparently we have a diploid genome, however, this fungus was described as haploid in cytometry. Where can I be wrong in my analysis?

**Comment by KamilSJaron** [comment]
Hi Fabian,

that fungus does not really look very monoploid to me. It actually look like a very clear tetraploid. Is that even possible?

Monoploid genomes show only one coverage peak, but your genome shows 3 to 4. And smudgeplot shows lots of k-mer pairs - namely k-mer pairs with ~150x and 50x coverages (the unannotated smudge) but also 100x and 100x (what is annotated as AB smudge). Given the gneomescope model and positions of the two smudges, I think the correct annotations would be AAAB and AABB respectively. When you do the plot, you can give a coverage prior 54 and the smudges should get correct labels.

Finally, it does not look like a population variability either. If there would be a genetic diveristy of individuals in the isolate, the peaks would not be spaced so evenly and the coverage ratios would not match precise ratios (0.25 and close to 0.5). So this genomic dataset looks terribly tetraploid to me.

Sorry about the misslables, I need to revisit the annotation algorithm soon, I have seen quite a few smudgeplots that were clearly misslabeled.

**Comment by fabianomenegidio** [comment]
Really when using coverage before 54, the stains must receive correct labels. I still need to think about the tetraploidy of this strain:

![saccharomyces_L15_n10_smudgeplot](https://user-images.githubusercontent.com/8346806/168430476-a36e323d-94b2-42ee-a0f3-a81001d620b9.png)

I noticed that the case is very similar to the Saccharomyces tutorial (by the way, this is a Saccharomyces).

https://github.com/KamilSJaron/smudgeplot/wiki/tutorial-saccharomyces

**Comment by KamilSJaron** [comment]
Oh cool, Sacharomyces quite wild when it comes to ploidy levels.

By the way, the last of any AB smudge would suggest this is not degenerated polyploid at all. I.e. there are no sequences that would be private only to two out of four haplotypes.

I will close it for now, feel free to reopen if anything.
