### ISSUE TITLE
Question about using corrected long reads for smudgeplot

### ISSUE THREAD

**Issue by davidprince84** [KamilSJaron/smudgeplot#102]
Hi,

Do smudgeplot (and Genomescope) work with corrected long reads (as outputted by Canu)? All the examples in the paper use short reads but I can't find anything in the paper or on GitHub that explicitly states that the software won't work with corrected long reads.

Thanks a lot,

David

**Comment by KamilSJaron** [comment]
Hi David thanks for asking, I added (moreless) [this question to FAQ](https://github.com/KamilSJaron/smudgeplot/wiki/FAQ#7-can-i-run-smudgeplot-on-long-reads).

the answer is, as always, it depends.

Corrected long reads are not as good as having regular Illumina or HiFi long reads, but if you have sufficient coverage it is very likely you will be able to fit the genomescope to the k-mer spectrum (the same apply to many other sequencing approaches like linked reads). To decide if there is a point in running smudgeplot, one needs to look at the k-mer spectrum - does it have meaningfully distinct genomic peaks? Are they at least-moreless separated from the sequencing errors? If the answer to both is yes, then smudgeplot should work as well.

**Comment by davidprince84** [comment]
Hi Kamil,

Thanks for your reply, and for adding the answer to the FAQ.

My coverage with correct reads is fairly low at the moment, so I'm going to try and generate more before I try genomescope.

**Comment by KamilSJaron** [comment]
If you would need more help, don't hesitate to reopen this issue, or open a new one
