### ISSUE TITLE
Haploid x Smudgeplot

### ISSUE THREAD

**Issue by fabianomenegidio** [KamilSJaron/smudgeplot#103]
Does Smudgeplot recognize haploid or assume polyploidy a priori?

I did some tests with Saccharomyces genomes described in the literature as haploid and I always get the diploid classification from Smudgeplot.

Is there any example of the haploid Smudgeplot?

**Comment by KamilSJaron** [comment]
Hi there, [check this section of FAQ](https://github.com/KamilSJaron/smudgeplot/wiki/FAQ#6-how-does-look-like-a-smudgeplot-of-a-haploid-species).

The whole idea is based on picking up coverage patterns of 'heterozygous" k-mers. So both completely, homozygous or haploid genomes will not really carry any signal that is used by the software (instead there will be co-founding signal of paralogs).

That should be clear however if you compare the smudgeplot with classical kmers spectra. Is the 1n coverage the same? Probably not, if it's really haploid, then smudgeplot will estimate it to be 2x as much as genomescope... Hope this'll help.
