### ISSUE TITLE
Lower coverage cutoff higher than upper coverage cutoff

### ISSUE THREAD

**Issue by manjumoorthy95** [KamilSJaron/smudgeplot#105]
The  genome with which we are working is on snake genome, from Genus Indotyphlops. We have performed shallow sequencing or skim-sequencing on the genome of this organism. We wanted to estimate the ploidy of the organism using kmer distribution.

It is seen that the lower coverage cut off (L) is being predicted higher than the upper coverage cutoff (U) for this organism. Any reason why this could happen?

Currently the L value I received is 139 and U as 88.

Help would be appreciated! Thanks.

**Comment by KamilSJaron** [comment]
The cutoff program is not trying to be in any way smart. You can [take a look](https://github.com/KamilSJaron/smudgeplot/blob/master/exec/smudgeplot.py#L116-L125) how it guesses L and U respectively.

L is 1.25x of the coverage of the first local minimum (we expect that there will be a detectable coverage peak associated with the genome sequencing)
U is 99.8% of the data.

So what likely happens is that you don't have any detectable coverage peak - which means that the first local minimum is actually among really high coverage, higher than 99.8% of your data.

That's the thing. If you have a genome skim (less than 5x of coverage), I am afraid you won't be able to use smudgeplot, it's not designed for such data. You can find more about [input here](https://github.com/KamilSJaron/smudgeplot/wiki/everything-about-input-data).

k-mers in general however can be useful. You can check what you can do with genome skims on [this workshop webpage](https://github.com/KamilSJaron/oh-know/wiki). Hope this helps.
