### ISSUE TITLE
What is "1n = 25" on the smudgeplot plots?

### ISSUE THREAD

**Issue by SuperYangZK** [KamilSJaron/smudgeplot#113]
In the figure "smudgeplot_smudgeplot_log10.png", what does the "1n = 25" mean? Looking forward to your reply!

**Comment by KamilSJaron** [comment]
Hi,

the 1n = XX, is the estimated 1n coverage. GenomeScope estimates the same value independently, checking that the two are in the same ballpark is a good way how to keep sanity. Note the same applies to linear version of the plot (the same estimate applies to both, it's the density that is on a log scale). Hope this helps.

**Comment by KamilSJaron** [comment]
I will close this issue for now, but if it's still unclear or if you run into more troubles, don't hesitate to reopen (if the issue is still the same) / or open a new issue (if it's not).
