### ISSUE TITLE
Problems installing smudgeplot

### ISSUE THREAD

**Issue by DaisyCrow** [KamilSJaron/smudgeplot#115]
I am having issues trying to install smudgeplot. 

I initially tried with conda, as recommended, and I am getting an error as follows:

![image](https://user-images.githubusercontent.com/132388481/235893296-558bc205-d23c-4ec0-865c-c42dad82fc12.png)

I have also tried with mamba, as it usually gives more helpful error messages, and got the following:

![image](https://user-images.githubusercontent.com/132388481/235893884-ae3e44d2-11c0-4f3a-b89e-48141c08bc21.png)

In both cases I was installing smudgeplot in a new environment, so it is not an issue of clashing with other programs installed in the same environment. 

I also tried following the instructions to git clone it, which also resulted in errors.

It looks like the issue might be that r-base 3.2.2 is no longer available on the channel? I tried installing that version of R using the biobuilds channel, but got the following error:

![image](https://user-images.githubusercontent.com/132388481/235900009-f85084e9-2ddf-442a-84c1-d14e32f3e0f6.png)

Any help you could give would be appreciated! 

Thanks!

**Comment by KamilSJaron** [comment]
Unfortunately I can't replicate it. I would need more details to track this down Daisy!

But I will keep it open if more people will run into the same trouble, we will have to do something about it.

**Comment by ferrojm** [comment]
Hi! 

I think had the same problem and I figured it out by removing and creating the environment again, and installing smudgeplot at the beginning and then the other packages! 

In my case, I used mamba instead of conda for installation

within the environment:
`mamba install -c bioconda smudgeplot`


cheers

**Comment by KamilSJaron** [comment]
That's good to know! Thank @ferrojm !
