### ISSUE TITLE
Can not find R package 'smudgeplot'

### ISSUE THREAD

**Issue by paka14** [KamilSJaron/smudgeplot#116]
I installed smudgeplot via conda. When 'smudgeplot_plot.R' was called, I got the following error.
    
    ### _Error in library("smudgeplot") : there is no package called ‘smudgeplot’
    Calls: suppressPackageStartupMessages -> withCallingHandlers -> library
    Execution halted_

 I can not find 'smudgeplot' in R, and can not install it. How can I do?

**Comment by KamilSJaron** [comment]
I am glad you figured it out :-)
