### ISSUE TITLE
Question about kmc parameters

### ISSUE THREAD

**Issue by ericgonzalezs** [KamilSJaron/smudgeplot#118]
I have just a simple question

When we run kmc like this:

         kmc -k21 -t16 -m64 -ci1 -cs10000 @FILES kmcdb tmp
         kmc_tools transform kmcdb histogram kmcdb_k21.hist -cx10000

Can the values in -cs and -cx affect the results in smudgeplot?

**Comment by ericgonzalezs** [comment]
Thank you very much, I ran Genomescope2 with the histogram produced by kmc and the histogram produced by canu, using HiFi reads. The histograms are very similar as you can see below 

Canu Histogram
![imagen](https://github.com/KamilSJaron/smudgeplot/assets/13828526/8769893a-ee0d-4ae2-afda-0101c5a47e9a)

Kmc histogram
![imagen](https://github.com/KamilSJaron/smudgeplot/assets/13828526/6a35abc6-b5c4-4a64-8773-cc5110bc2d73)

These are the results with the canu histogram:
![imagen](https://github.com/KamilSJaron/smudgeplot/assets/13828526/d9e9b906-ff51-49b2-9e97-637ae2676c45)

And this one with the kmc histogram
![imagen](https://github.com/KamilSJaron/smudgeplot/assets/13828526/5e8d3303-0ae0-403b-a6f1-604691b5daee)

The shape of the histogram is the same, but the frequency and genome size is quite different. What could be the explanation for this? Many thanks.

**Comment by KamilSJaron** [comment]
I suspect this will be the explanation: https://kamilsjaron.github.io/peculiar-genomic-observations/biological/2020/01/crayfish.html
