### ISSUE TITLE
issue about smudge_pairs

### ISSUE THREAD

**Issue by linshengnan09** [KamilSJaron/smudgeplot#119]
**What did you do**

Tell us about the problem. what is the version of the software you used (smudgeplot -v)? What was the input (possibly with a few example lines)? What is the command you run? What is the error output you get? And what you have expected to see instead?
hi，I couldn't get the smudge_pairs subroutine in KMC.

**Comment by KamilSJaron** [comment]
Hi, sorry to hear that, but without more info, there is no way we can help you...

**Comment by linshengnan09** [comment]
您好，您的邮件我已收到。祝生活愉快，工作顺利！

**Comment by linshengnan09** [comment]
As the issue ["Killed process on smudgeplot hetkmers #77"](https://github.com/KamilSJaron/smudgeplot/issues/77),  I want to install tbenavi1/KMC with smudge_pairs to solve this problem.Unfortunately, I didn't get the smudge_pairs when I installed tbenavi1/KMC.

**Comment by KamilSJaron** [comment]
What did you do to install it? Did you try something like:

```
make smudge_pairs
```

that should give you some sort of log, if the log has an error, what error it is?

Anyway, I can't help you much with the little effort you put in reporting the problem. If would like to get some help you need to be A LOT more verbose - describe what system you have (if relevant), what exactly you tried to do (the commands you executed, not "install the software"), what was error you got...
