### ISSUE TITLE
Salix RAD-data smudgeplots

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/smudgeplot#122]
Hi, I see that the issue is closed long before. But i need some recommendations regarding my Smudgeplots. Because they are not making sense and I am lost at the moment. So i though it might be helpful to write you all. Please help me!

I have a 120bp single-end RadSeq data (>30x coverage) for a number of _Salix_ species, which I want to determine the ploidy level using the Smudgeplot. I run following commands:

```
kmc -k21 -t16 -m64 -ci1 -cs10000 "${file}.fastq" "${file}_kmcdb" tmp
    kmc_tools transform "${file}_kmcdb" histogram "${file}_kmcdb_k21.hist" -cx10000
    L=$(smudgeplot.py cutoff "${file}_kmcdb_k21.hist" L)      # Determines automatically; L should be like 20 - 200
    U=$(smudgeplot.py cutoff "${file}_kmcdb_k21.hist" U)     # U should be like 500 - 3000			    
    kmc_tools transform "${file}_kmcdb" -ci"$L" -cx"$U" reduce "${file}_kmcdb_L${L}_U${U}"
    kmc_dump "${file}_kmcdb_L${L}_U${U}" "${file}_kmcdb_L${L}_U${U}_coverages.tsv" "${file}_kmcdb_L${L}_U${U}_pairs.tsv" > "${file}_kmcdb_L${L}_U${U}_familysizes.tsv"
    kmc_tools transform "${file}_kmcdb" -ci"$L" -cx"$U" dump -s "${file}_kmcdb_L${L}_U${U}.dump"
    smudgeplot.py hetkmers -o "${file}_kmcdb_L${L}_U${U}" < "${file}_kmcdb_L${L}_U${U}.dump"
    smudgeplot.py plot "${file}_kmcdb_L${L}_U${U}_coverages.tsv" -o "${file}_kmcdb_L${L}_U${U}_smudgeplot" -t "${file}" -q 0.99
```

  and then got this result for Salix retusa (NW17_076_L10_U520 (x41 coverage) and T2221 (x46) :
![S_retusa_NW17_076_kmcdb_L10_U520_smudgeplot_smudgeplot_log10](https://github.com/KamilSJaron/smudgeplot/assets/141621511/9b31648a-d920-4dd5-9715-4797ae971988)
![S_retusa_NW17_076_kmcdb_L10_U520_smudgeplot_smudgeplot](https://github.com/KamilSJaron/smudgeplot/assets/141621511/80197a8f-36ec-4251-9df0-57984b0ae607)

This species/individuals should be an **octoploid** according to our flow cytometry, but the Smudgeplot suggests **triploid** or **diploid**. 

I did not give a constant number for L and U, because it showed me an error: 
"detecting two smudges at the same positions, not enough data for this number of bins lowering number of bins to 	35
detecting two smudges at the same positions, not enough data for this number of bins lowering number of bins to 30 ...". 

When I checked GenomeScope, for both individuals, it failed to converge:
![Screen Shot 2023-08-07 at 10 54 51 AM](https://github.com/KamilSJaron/smudgeplot/assets/141621511/935b327f-d97b-40d4-886b-b2be9e216ce6)
![Screen Shot 2023-08-07 at 10 56 05 AM](https://github.com/KamilSJaron/smudgeplot/assets/141621511/70648ff0-2c7e-4574-84b7-3dd900153fae)

I have more than 100 individuals that are not fitting to my expectation of ploidy level.
So my question is, what am I possibly doing wrong? 
What could be adjusted to get more precise estimation?

_Originally posted by @OyukaKh in https://github.com/KamilSJaron/smudgeplot/issues/17#issuecomment-1667475610_

**Comment by KamilSJaron** [comment]
Hi @OyukaKh,

for new problems we like to have new opened issues, so I moved your messages here.

Nor smudgeplot or genomescope is designed to work on RAD data, sorry it was no on the wiki, I added a section it to [FAQ](https://github.com/KamilSJaron/smudgeplot/wiki/FAQ#9-can-i-use-smudgeplot-on-reduced-representation-sequencing) now.

The last sample S_retusa_T2221 looks like it could work, but for some reason the y axis is very stretched and the smudge is not well separated from the error line, is there a chance you could post genomescope of that sample as well?

**Comment by KamilSJaron** [comment]
Duplicit to #121

**Comment by KamilSJaron** [comment]
I am by no means expert on RADseq, and as a matter of fact, I foolishly wrote optical duplicates, instead of just "duplicates", because in RAD most of them will be PCR duplicates. Meaning, it's the same template DNA that was sequenced twice, those should not be weighted as the two independent observation of the same genomic location and they do contribute to coverage variation.

Is it ddRAD or sdRAD? I think for ddRAD it's quite complicated (if not impossible), but for the single end, you can remove all the fragments of the exactly same size (you expect the trailing end will vary in size). I really don't know what tools people use for this (I know it from talks only).

But most of all, I would really try some reference approach.  There is at least one chromosomal willow out there (https://www.ncbi.nlm.nih.gov/datasets/genome/GCA_029030765.1/). I think you would have easier times looking at aligned piles or reads than k-mers. The gneome is not too large anyway, so hopefully it will easy to align too.

**Comment by OyukaKh** [comment]
I see! Thanks a lot for the suggestion and prompt replies!
We have sdRAd data. So, we would go for aligning :-).
Thanks Kamil!
