### ISSUE TITLE
Difference between the result of smudgeplot and the real ploidy of species

### ISSUE THREAD

**Issue by curtainDian** [KamilSJaron/smudgeplot#126]
Hi, Kamil,
Thanks for detailed description of the software, and smudgeplot offers me much convenience. I have WGS data of over 200 species, and these species are in the same genus, with genome size and ploidy varying greatly (400Mb-1Gb & 2x-10x).
I used the combination of jellyfish and smudgeplot,

```
L=$(smudgeplot.py cutoff ./${i}/${i}_21kmer.histo L)
U=$(smudgeplot.py cutoff ./${i}/${i}_21kmer.histo U)
echo $L $U 
~/miniconda3/envs/jellyfish/bin/jellyfish dump -c -L $L -U $U 21kmer_${i} | smudgeplot.py hetkmers -o ./smudgeplot_hetkmer/21kmer_${i}_pairs
```

and then I got the result that nearly 90% of the species are diplod. Therefore, I wish you could offer me some advice. I reviewed the issue in the past and saw the advice about increase $U and reduce $L, but whether it will impact on the accuracy of result? After all, ploidy estimation is based on the results of kmc/jellyfish.

**Comment by KamilSJaron** [comment]
Hi,

I don't see your last issue, could you please link it or advice me how can I find it?

200 species of the same genus is a lot of species; I presume you also did some GenomeScope profiling, would you like to post here a few genomescope plots and smudgeplot of some of the diploids and some of the non-diploid samples?

We just finished a beta-version of the next generation of smudgeplot, if you would like to give it a try, I can give you instructions on how to use it. Of course, if you have the two hundred done already, I do understand you would not like to redo that (but for what its worth, the new version is a LOT LOT faster)

**Comment by KamilSJaron** [comment]
Also, is there a reason why you are sceptical about 90% being diploid?

**Comment by KamilSJaron** [comment]
Uh, finally, I just noticed you have just 2-10x coverage, it's very likely smudgeplot won't be very useful, it is not made for genome skimming data, perhaps some of the 10x datasets might have a decent smudgeplot, but that is very very low coverage for smudgeplot.

**Comment by curtainDian** [comment]
Hi, Kamil,
Thanks for your reply, and I am really sorry for late reply. 
I checked the genomescope results of my data to get the genome size, and I found that coverage is surely not adequate (＜10×). So could you please offer me other advice (except smudgeplot) ? Or there is no solution to estimate my species' ploidy according to my data ?
Thanks a lot !

**Comment by KamilSJaron** [comment]
What's the system? Perhaps you could think of some form of reference based technique? I don't think there are any out-of-box solutions for such problem at the moment I am afraid.
