### ISSUE TITLE
FEEDBACK WANTED: Installation and running instructions for beta-version of Smudgeplot 0.3.0 Oriel

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/smudgeplot#129]
This issue is for the brave beta-testers that would like to test the beta-version of the lastest version of Smudgeplot 0.3.0 Oriel. 

Fist, get the smudgeplot repository
```
git clone https://github.com/KamilSJaron/smudgeplot.git
```
then pull also the development branch
```
cd smudgeplot
git branch sploidyplot #create a branch for the developmental version
git checkout sploidyplot #checkout to that branch
git pull origin sploidyplot #pull the new version locally
```
Now you downloaded the beta-version. There is a [readme file](https://github.com/KamilSJaron/smudgeplot/tree/sploidyplot) with installation instructions and everything you need to know to run the beta-version (hopefully, it's beta after all). 

Let me know if it works for you!

**Comment by sujaikumar** [comment]
or in one command :-)

```
git clone -b sploidyplot https://github.com/KamilSJaron/smudgeplot
```

**Comment by KamilSJaron** [comment]
I should have thought there is a simpler solution, thanks Sujai!

**Comment by bm-silva** [comment]
Hi @KamilSJaron,

I successfully installed and ran smudgeplot 0.3.0 without any issues. However, I have some inquiries regarding the FastK and PloidyPlot parameters:

FastK:

-t: Generates a table of sorted k-mers and counts greater than or equal to the specified level.
PloidyPlot:

-e: Sets the count threshold below which k-mers are considered erroneous.
smudgeplot.py:

-n N: Sets the expected haploid coverage (defaults to estimation from data).
If I misuse these arguments, could it lead to erroneous ploidy predictions? Regarding the -n flag, can it be left blank? Additionally, could a highly repetitive genome contribute to inaccurate predictions?

Thank you for your assistance!

**Comment by KamilSJaron** [comment]
Hi @bm-silva, 100% yes.

-t can be picked fairly small (4 is fairly common); it's good to see the low coverage kmers in at least the coverage histogram
-e is the parameter L in `smudgeplot.py hetmers` interface. That should be decided upon inspection of the histogram; usually >10 for any dataset that was intended for reference genome sequencing (if you will get a messy smudgeplot it probably means you would not reconstruct the genome well anyway)
-n is a parameter I would not recommend to use unless you think you really know what the coverage should be.

**Comment by KamilSJaron** [comment]
Of course you can, the question is if you trust it. There is no harm in doing both. The smudgeplot rule of thumb is "if it looks right, it probably is"

**Comment by KamilSJaron** [comment]
I will close it, and will open a new feedback thread with the new release
