### ISSUE TITLE
Problems compiling (and running) smudge_pairs

### ISSUE THREAD

**Issue by RSchley** [KamilSJaron/smudgeplot#135]
Hi there, I am experiencing two problems with smudge_pairs on Rocky Linux 8.8 (Green Obsidian).

The first is that I cannot compile KMC from the branch at **tbenavi1/KMC** when I run it thusly:
`git clone https://github.com/tbenavi1/KMC.git
cd KMC
make`

I get the error:
**/usr/bin/ld: cannot find -lpthread
/usr/bin/ld: cannot find -lstdc++
/usr/bin/ld: cannot find -lm
/usr/bin/ld: cannot find -lc**

Granted, this is likely something to do with my cluster lacking some libraries for gcc or something. 
However, when I do manage to compile tbenavi1/KMC on other systems, I run smudge pairs like this:

```
mkdir tmp
ls seqname_*.fastq.gz > FILES

kmc -k21 -t12 -m40 -ci1 -cs10000 -fq @FILES seqname_k21 tmp/
kmc_tools transform "$SEQNAME"_k21 histogram seqname_k21.hist -cx10000

L=$(smudgeplot.py cutoff seqname_k21.hist L) 	#### L should be like 20 - 200
U=$(smudgeplot.py cutoff seqname_k21.hist U) 	#### U should be like 500 - 3000
echo $L $U 							#### these need to be sane values

kmc_tools transform seqname_k21 -ci"$L" -cx"$U" reduce seqname_k21_L"$L"_U"$U"
smudge_pairs seqname_k21_L"$L"_U"$U" seqname_k21_L"$L"_U"$U"_coverages.tsv seqname_k21_L"$L"_U"$U"_pairs.tsv > seqname_k21_L"$L"_U"$U"_familysizes.tsv
```

But it gives no output at all, and eventually is killed by the out of memory handler when allotted 40g of memory. The largest input kmc_suf file is around 2GB. Does smudge_pairs usually need more memory, and is it normal to have no intermediate output from smudge_pairs?

Thanks very much for developing this great tool!

**Comment by KamilSJaron** [comment]
We are quite far along releasing a new version of smudgeplot that does not use KMC anymore (the BGA23 tutorial of smudgeplot is already on the new version). THe new version is substantially more efficient!

Regarding compilation on the cluster; No idea, perhaps @tbenavi1?

**Comment by KamilSJaron** [comment]
Just look at the BGA tutorial (https://github.com/BGAcademy23/smudgeplot) and the sploidyplot branch, the info should be there.

**Comment by RSchley** [comment]
Amazing! Thank you very much.

**Comment by KamilSJaron** [comment]
WIll be resolved in the next release by replacing the k-mer pair search engine
