### ISSUE TITLE
Error in estimate_1n_coverage_1d_subsets(total_pair_cov, minor_variant_rel_cov)

### ISSUE THREAD

**Issue by ferrojm** [KamilSJaron/smudgeplot#143]
Hi, Kamil!

I had this issue when trying to generate the plot :
```
Error in estimate_1n_coverage_1d_subsets(total_pair_cov, minor_variant_rel_cov) :
  unused argument (minor_variant_rel_cov)
```
The inputs were created with KMC k=21 (not the tbenavi1/KMC version), using as coverage range L=24 and U=3800 (values obtained with smudgeplot.py cutoff). I am running the conda version (v.0.2.5). 

###############
####UPDATE#####
###############

Following your comments on other issues, I counted kmers with FastK, but I also got stuck when using smudgeplot.py
Although being another issue not realeted to this one, for not creating hundreds of different posts here it goes!

My commands:

`FastK -v -t4 -k21 -T6 reads.fastq.gz -NSMUDGEPLOT -Ptemp/ `
`smudgeplot.py hetkmers -o SMUDGEPLOT_k21_pairs SMUDGEPLOT.ktab`

and the error:

![image](https://github.com/KamilSJaron/smudgeplot/assets/58785132/ca99e13c-5efd-4a15-bad4-c01e25beca1a)

Thanks!

**Comment by KamilSJaron** [comment]
Hi, you got to install the version in `sploidyplot` branch: https://github.com/KamilSJaron/smudgeplot/tree/sploidyplot

Sorry about the long silence, I am now in the middle of debugging it before the release and that's going to solve most of these problems people have now.
