### ISSUE TITLE
Interpreting a possible haploid

### ISSUE THREAD

**Issue by jacquelinemattos** [KamilSJaron/smudgeplot#147]
Hi,
I'm having trouble understanding my smudgeplot. 
We have some reasons to believe that our species' genome should be a haploid, but based on what you replied on another thread regarding the 1n coverage peak, we are no longer sure about the ploidy. Could you please help figure it out?
It's a fungal species that was sequenced using PacBio HiFi. 

Our plot looks like this: 

![pucciniasilphii_ploidy_smudgeplot](https://github.com/KamilSJaron/smudgeplot/assets/34355961/e711c8eb-d0a8-4069-a6f4-fff6cc1acd50)

And this is the genomescope profile for the same genome: 

![transformed_linear_plot](https://github.com/KamilSJaron/smudgeplot/assets/34355961/c0384dd0-7291-4522-93f5-a22425fcf835)

If you could please help understanding this ploidy, it would be greatly appreciated. 
Thanks so much!

**Comment by jacquelinemattos** [comment]
Hi @KamilSJaron,
Thanks so much for your response! This is really helpful. 
Yes, we're working with a Puccinia sp. isolate (a rust fungus). We also thought it would be a haploid, so I'm guessing we could conclude that afterwards? 
Thank you!

**Comment by KamilSJaron** [comment]
Oooh, a rust fungus! Cool!

Yeah, i would be comfortable thinking that. I would try to fit the haploid model in genomescope (-p 1) so you have a meaningful genome size estimate. Then keep an eye on the size of the assembled genome. if they would be a lot different you can post here again and we can give it a think again.

**Comment by jacquelinemattos** [comment]
Hi @KamilSJaron! 
Oh, for sure, I'll do that. But this has already been super helpful!! We really wanted to underestand the ploidy of this species and now it seems to be much more clear! 
Thank you so much for you help! I'll come back and post again if needed, for sure.

**Comment by KamilSJaron** [comment]
Great, I will close for now, feel free to reopen
