### ISSUE TITLE
Hexaploid Plant Analysis and Genome Assembly Questions

### ISSUE THREAD

**Issue by BioOmics** [KamilSJaron/smudgeplot#148]
We are studying a polyploid plant. By inputting different `-p` values (p=2, 3, 4, 5, 6) into GenomeScope, we obtained the following figA and figC. As shown, the model fit in figA is the best. Then, using `smudgeplot.py hetkmers`, we extracted the k-mers from GenomeScope at `-p 6` to create figB. We currently have the following questions:

**1.** Can we infer that this plant is hexaploid?
**2.** If it is hexaploid, can we deduce that this plant is a homologous hexaploid (6A) rather than an allopolyploid (5A1B or 4A2B, etc.)?
**3.** If it is a homologous hexaploid (6A), is it sufficient for genome assembly to assemble only one haplotype (A)?
**4.** Finally, this question pertains to GenomeScope, but I believe it is better to ask you: Should the estimated genome size be 221 Mbp × 6 = 1.33 Gbp?

We hope to receive your valuable insights.
![fig](https://github.com/KamilSJaron/smudgeplot/assets/90701365/06b5c009-f0ed-4f0c-a74b-820eb51ffa76)

**Comment by KamilSJaron** [comment]
1. Looks fairly convincing.
2. "homologous hexaploid" is a strange expression. I would rather use word "autohexaploid", but also looks quite probable - allopolyploids are nearly always come in pairs (e.g. 2 haplotypes from one, 4 from the other, etc). I guess it's technically possible it's allo with only a single haplotype comping from a distant relative, but I would say that's unlikely. Once you assemble the genome you should be able to see if all the variants are part of a single haplotype (i.e. large fraction the minor variants within the genome would be phasable)
3. That is hard to say, hexaploids are hard to assemble and this one is quite heterozygous, I imagine the assembly will be a bit messy. Assemblers do not have evolutionary models embeded, auto- allo- matters very little to them, what matters is local similarity of haplotypes - so if there are some larger variants you might end up with inflated assembly size and you will have to purge those duplications.
4. Monoploid genome represetation (the one people expect) should be ~221 Mbp - if you would be purging the primary assembly, this is approximately the span you should aim for. If you would like to have a fully phased hexaploid genome, then you expect 1.33 Gbp (doable with diploids sometimes, would be very difficult with hexaploid, I imagine you don't want this).

**Comment by BioOmics** [comment]
Thank you for your detailed response; it has been immensely helpful to us. After some reflection over the past few days, we realize that we still have additional work to undertake. You may go ahead and close the issue for now. Rest assured, we may reach out to you again for further guidance in the future if necessary.

Thank you very much!
