### ISSUE TITLE
SPloidyPlot detecting two smudges at the same positions warning

### ISSUE THREAD

**Issue by mellamosummer** [KamilSJaron/smudgeplot#149]
Hi Kamil!

I am trying out SPloidyPlot and could use some help troubleshooting the outcome!

I used following command to generate the smudgeplot:

```
FastK -v -t4 -k31 -M16 -T4 *gz -NFastK_Table
PloidyPlot -e12 -k -v -T20 -oFastK_Table
smudgeplot.py plot kmerpairs_text.smu -n 15 -t Geranium_maculatum -o trial_run
```
and it looks like this:

[trial_run_smudgeplot.pdf](https://github.com/user-attachments/files/15571422/trial_run_smudgeplot.pdf)
[trial_run_smudgeplot_log10.pdf](https://github.com/user-attachments/files/15571432/trial_run_smudgeplot_log10.pdf)

Flow cytometry estimates the genome size around ~2Gb and chromosome counts are reported as 2n=52. The most recent phylogeny for this groups suggests it is in a clade of allotetraploids.

I am sharing because I recieved the following error from SPloidyPlot in trial_run_warnings.txt:

```
detecting two smudges at the same positions, not enough data for this number of bins lowering number of bins to         35
detecting two smudges at the same positions, not enough data for this number of bins lowering number of bins to         30
detecting two smudges at the same positions, not enough data for this number of bins lowering number of bins to         25
!! Warning, the two types of estimates of 1n coverage differ a lot (    27.8    and     13.643544992789 )
i.e. at least of one of the smudgeplot methods to estimate the haploid coverage got it wrong
Using subset estimate instead of highest peak estimate (less precise but also less often completely wrong)
Does the smudgeplot look sane? Is at least one of the 1n estimates close a GenomeScope estimate?
You can help us imrove this software by sharing this strange smudgeplot on https://github.com/KamilSJaron/smudgeplot/issues.
!! Warning, your coverage filter on the lower end (L =  12      ) is higher than half of the 1n coverage estimate ( 1n / 2 =    7.5
If the real 1n coverage is half of your estimate you would not picked it up due to the filtering.
If you have sufficient coverage, consider reruning the analysis with lower L (something like (1n / 2) - 5)
One good way for verificaiton would be to compare it to GenomeScope estimate of haploid coverage
```
I have also generated a previous GenomeScope plot using jellyfish for kmer counting. The data used are for both smudgeplot and genomescope are PacBio HiFi reads. Here is the GenomeScope plot. 

![transformed_linear_plot_kmer61_PacBioHiFi](https://github.com/KamilSJaron/smudgeplot/assets/95707842/b8e7aa6a-dd60-4bf4-9420-dc3c48ae8595)

Could you help make sense of this result/error? 

Thanks!!

**Comment by KamilSJaron** [comment]
Hi Summer!

Long story short - the labeling algorithm is broken, I am scratching my head over figuring out a better way to do that so we don't run into these silly inference problems. Honestly, it looks like a perfectly harmless smudgerplot, I have no idea why it got so strangely annotated, could you share me the .smu file by any chance?

As for your data, if it's an allopolyploid, it's most likely a degenerated allo- something - there are no obvious kmer bumps for more than 2n k-mers, meaning that the homoelogous genomic copies are substantially diverged (so not really a polyploid sensu stricto; Let me guess, is this a salmonid?).

The smudgeplot SHOULD have labeled the bright smudge as AB and estimated 1n coverage similar to genomescope. I have really no idea what went wrong with it.

**Comment by mellamosummer** [comment]
Hi Kamil,

Thanks for your quick response! I've attached the SMU file.

After reading about the parameters more closely, I did another run changing the n parameter to the genome scope kcov – 26 (previously I just used the n specified in the tutorial but realized that's not appropriate!). I've attached the new smudgeplot which looks closer to what you described! And this is not a salmonid – it is an herbaceous, perennial plant native to the eastern US. 🙂

________________________________

**Comment by mellamosummer** [comment]
[trial_run_smudgeplot_log10.pdf](https://github.com/user-attachments/files/15637094/trial_run_smudgeplot_log10.pdf)
[trial_run_smudgeplot.pdf](https://github.com/user-attachments/files/15637098/trial_run_smudgeplot.pdf)
[kmerpairs_text.smu..txt](https://github.com/user-attachments/files/15637183/kmerpairs_text.smu.txt)

**Comment by KamilSJaron** [comment]
Ah, that explains a lot - if the coverage prior is off, that can confuse the algorithm a lot. 

Thank you for the dataset though, I will add herbaceous to the testing battery.
