### ISSUE TITLE
script execution never ends （Extremely Large .jf Files）

### ISSUE THREAD

**Issue by GLking123** [KamilSJaron/smudgeplot#151]
Hello, due to my data being too large, it has been running for several days.

`L=$(smudgeplot.py cutoff 21kmer.histo L)
U=$(smudgeplot.py cutoff 21kmer.histo U)
echo $L $U
jellyfish dump -c -L $L -U $U merged_counts.jf | smudgeplot.py hetkmers -o kmer_pairs
`

**merged_counts.jf 299G**

The script has been running for **10 days**.Consumed **4TB** of memory. 

For the above question, could you provide some debugging suggestions? Thank you for your valuable time and assistance. I sincerely look forward to your response！

**Comment by KamilSJaron** [comment]
Hi, try the development version, check https://github.com/KamilSJaron/smudgeplot/tree/sploidyplot, it's based on a much much faster code that scales for any genome size

**Comment by GLking123** [comment]
Hi, How should I use the beta version?
I have already generated a 300G 'merged_counts.jf' file with Jellyfish. How can I use it together with the beta version? Can it be used this way?
`L=$(smudgeplot.py cutoff 21kmer.histo L)
 U=$(smudgeplot.py cutoff 21kmer.histo U) 
echo $L $U 
jellyfish dump -c -L $L -U $U merged_counts.jf
PloidyPlot -e12 -k -v -T4 -odata/Scer/kmerpairs merged_counts.jf
smudgeplot.py plot -n 15 -t Sacharomyces -o data/Scer/trial_run data/Scer/kmerpairs_text.smu
`
For the above question, could you provide some debugging suggestions? Thank you for your valuable time and assistance. I sincerely look forward to your response！
