### ISSUE TITLE
PloidyPlot: Table part ./.finall.ktab.1 is missing ?

### ISSUE THREAD

**Issue by GLking123** [KamilSJaron/smudgeplot#154]
Hi,

I attempted the new FastK. I ran multiple datasets separately and then used Fastmerge for the final combination.

The commands are as follows:

`FastK -v -t4 -k31 -T20 -P$outdir -M20 -N$outdir $sourecedir`

`Fastmerge -ht -T100 -P$outdir finall 01 02 03 04 05 06 07 08 09 10 11 12 13 14 16`

![image](https://github.com/KamilSJaron/smudgeplot/assets/71629239/b0685e24-18c4-488a-8fc2-f70d64aede24)

However, when running `PloidyPlot -e4 -k -v -T50 -o$outdir finall`, an error occurs.
PloidyPlot: Table part ./.finall.ktab.1 is missing ?

For the above question, could you provide some suggestions? Thank you for your valuable time and assistance. I sincerely look forward to your response！

**Comment by KamilSJaron** [comment]
Good question. Gene, can you run PloidyPlot algorithm on fast merged files @thegenemyers?

**Comment by GLking123** [comment]
I apologize for bothering you, but I'm currently unsure who else to ask. I'm stuck at the step of determining ploidy. @KamilSJaron

**Comment by KamilSJaron** [comment]
Hi @GLking123, FastK makes bunch of dotted filed files as well as the visible .ktab files, did you by any chance move them around or something? The commands you show should work... (at least Gene was convinced they should)

In the meantime, can you simply make yourself one kmer database from all the read files right away and do the ploidy prediction on that? That will work for sure even if it's a bit of redundant compute...

**Comment by GLking123** [comment]
Thank you for your reply. I will try many times according to your suggestion!

**Comment by GLking123** [comment]
Hi @KamilSJaron , I employed your approach, and the speed was tenfold quicker than previously. What I am eager to understand is that GenomeScope 2.0 assessed it to be autoteploid based on aaab > aabb, yet smudgeplot predicted it to be diploid. How do you account for this?

`FastK -v -t4 -T40 -Ptmp -M220 -N$outdir $sourecedir`
`PloidyPlot -e12 -k -v -T40 -Ptmp -o/Fask/new_smudgeplot $outdir`
`smudgeplot_plot.R -i "/Fask/new_smudgeplot_text.smu" -o "smudgeplot" -t "smudgeplot" -col_ramp "viridis"`

![image](https://github.com/user-attachments/assets/d36deffa-b519-49f6-b763-626dd67a36c1)

<img width="301" alt="image" src="https://github.com/user-attachments/assets/14375afe-3cbf-4e87-806e-099f72183ecc">


For the above question, could you provide some suggestions? Thank you for your valuable time and assistance. I sincerely look forward to your response！

**Comment by GLking123** [comment]
[Allium_tuberosum_alt_alt_smudgeplot.pdf](https://github.com/user-attachments/files/16922298/Allium_tuberosum_alt_alt_smudgeplot.pdf)
[Allium_tuberosum_alt_alt_smudgeplot.pdf](https://github.com/user-attachments/files/16922307/Allium_tuberosum_alt_alt_smudgeplot.pdf)

**Comment by GLking123** [comment]
![image](https://github.com/user-attachments/assets/bef5c26c-0835-4b37-ad4b-f9d755950f0b)
![image](https://github.com/user-attachments/assets/1e33c0c5-52ef-4d82-b6be-6350fa9a2a2d)
