### ISSUE TITLE
Should 1n coverage in smudgeplot be equal to the lambda in genomescope for allopolyploid?

### ISSUE THREAD

**Issue by wu116** [KamilSJaron/smudgeplot#157]
Hello!

I am working on a allopolyploid plant (2n=4x=40) which has been reported that the DNA 2C value is 0.80 pg. And I has already assembled its and got an haplotype-resolved assembly (A1A2B1B2) with 630 Mb. The synteny analysis with the model plant also proves that this species is a allotetraploid.

The problem is when i used the default parameters to run genomescope and smudgeplot, they seem to give different estimated 1n coverage: ~42x for genmescope and ~83x for smudgeplot.

**CODE:**
`genomescope.R -i NGS_km19.tsv -o km19_p4 -k 19 -p 4`
`smudgeplot.py plot -i kmer19_pairs_coverages.tsv -k 19`
**PLOT:**
![transformed_linear_plot](https://github.com/user-attachments/assets/126a55d3-fb53-4bc6-91d3-120961d97212)
![smudgeplot_smudgeplot_log10](https://github.com/user-attachments/assets/efb7d3c8-9d8b-46f5-a64c-07b6be39cb12)

**For genomescope**, I think the estimated genome size is wrongly doubled, because the little peak in ~42x was consider as heterozygous peak by genomescope. Am i right?

So I assigned the lamba parameter as 84 and re-ran genomescope:
`genomescope.R -i NGS_km19.tsv -o km19_p4 -k 19 -p 4 -l 84`
![transformed_linear_plot](https://github.com/user-attachments/assets/4283465d-c419-4457-964a-747f6d033f42)
At this time, the estimated genome size seems well fit our haplotype-resolved assembly size. (150 * 4 = 600)

However, **for smudgeplot**, use heterozygous peak coverage (~84x) as the 1n coverage seems to predict my species as a diploid.

If I assigned the the expected haploid coverage parameter as 42 and re-ran smudgeplot:
`smudgeplot.py plot -i kmer19_pairs_coverages.tsv -k 19 -n 42`
![smudgeplot_smudgeplot_log10](https://github.com/user-attachments/assets/6ef7d6c2-7dd4-4451-a7c8-a8924023eb58)
At this time, the estimated genome ploidy seems well fit our priori knowledge about this species. (allopolyploid, AABB)

Above all, i am still confused about if the 1n coverage in smudgeplot should be equal to the lambda in genomescope or not? If not, how could i explain those peaks in the kmer histogram plot? Like 42x, 84x, 168x in my case.

Could you please to give me a hand? THANK!!!

**Comment by KamilSJaron** [comment]
Hi @wu116, given your assembly is 600Mbp, I would say the model that predict 300Mbp haploid size the right one - You assembled 2 haplotypes, 300Mbp each. All fits well.

My bet is that within A and within B signal is a lot lot weaker than A vs B homoeologs signal to the extend, you don't really see the 2n smudge. I suspect there will be only very negligible levels of within A / B heterozygosity.

Smudgeplot is based on the idea of heterozygosity, the automated inference won't give you a good guess for homozygous genomes.

**Comment by wu116** [comment]
Thanks for helping! There's one last thing I want to confirm: for some other typical species, is the meaning of 1n coverage in smudgeplot the same as the lambda in genomescope? I've checked some cases in wiki and issues, the answer might be yes. But I'm unable to determine for a while, their relationship is hard to understand for me :(

**Comment by KamilSJaron** [comment]
Yes! lambda in genomescope is the parameter for 1n coverage - so they are the same thing. The two tools are (intentionally) infer the 1n coverage separately. If they disagree, it forces users to figure out what is going on which is usually important for understanding the genome.
