### ISSUE TITLE
The estimated multiplicity does not meet expectations and differs significantly

### ISSUE THREAD

**Issue by GLking123** [KamilSJaron/smudgeplot#161]
Hi @KamilSJaron , I employed your approach, and the speed was tenfold quicker than previously. What I am eager to understand is that GenomeScope 2.0 assessed it to be autoteploid based on aaab > aabb, yet smudgeplot predicted it to be diploid. How do you account for this?

```
FastK -v -t4 -T40 -Ptmp -M220 -N$outdir $sourecedir
PloidyPlot -e12 -k -v -T40 -Ptmp -o/Fask/new_smudgeplot $outdir
smudgeplot_plot.R -i "/Fask/new_smudgeplot_text.smu" -o "smudgeplot" -t "smudgeplot" -col_ramp "viridis"
```

![image](https://github.com/user-attachments/assets/f59a4537-d9fe-4042-891b-ec9fb851a835)
![image](https://github.com/user-attachments/assets/8afe5b9c-3e20-4dc0-a2ce-4718ab3a95d6)
![image](https://github.com/user-attachments/assets/ab81eb7d-41b0-45ab-83ff-365e37980c05)
![image](https://github.com/user-attachments/assets/612e3a22-46f1-4b16-8135-61ed81779bab)

For the above question, could you provide some suggestions? Thank you for your valuable time and assistance. I sincerely look forward to your response！

**Comment by KamilSJaron** [comment]
Hi @GLking123, I have very hard times beliving the two plots (smudgeplot and genomescope) were made out of the same data or using the same parameters. The k-mer coverage estimates of genomescope and smudgeplot must make sense (actually, be same) and in your case one predicts ~25x and the other ~40x, that's quite a difference... 

I suspect the difference could be in the k you used for one and the other. What k did you use for the fastK kmer database will be the k that is used for smudgeplot. Looking at the command, it seems it's going to be the default, which I don't remember what is, but I doubt 35.

I would advice to redo also the k-mer histogram from the very same kmer database by FastK, and redo the genomescope plot. Then we could try to find an interpretation.

**Comment by GLking123** [comment]
Hi @KamilSJaron 
I have taken your suggestions into account, and below is my latest attempt.

`FastK -v  -t4 -k35 -T40 -Ptmp -M220 -N$outdir $sourecedir
PloidyPlot -e12 -k -v -T40 -Ptmp
`
I have two types of data, one is hifi and the other is illumina.The same treatment：
hifi:
![image](https://github.com/user-attachments/assets/fa0538c4-ca3e-41cf-b7a2-6fca63fef8f0)
illumina:
![image](https://github.com/user-attachments/assets/b56909ef-af11-4503-9b89-1bc44b18b251)

I also performed a merge：
`Fastmerge -ht -T35 -P$outdir finall   hifi  illumina 
PloidyPlot -e12 -k -v -T40 -Ptmp
`
merge：
![image](https://github.com/user-attachments/assets/828f0706-432d-43e2-aecf-d596442dc643)

**Comment by GLking123** [comment]
@KamilSJaron Because my Illumina data is not very large, in the Genomescope plot, I first merged the HiFi data with the Illumina data using KMC, and the result was a homologous tetraploid. However, in the Smudgeplot plot, I used Fastk with the same K value and three modes of data from both types, but the results were not very satisfactory.

**Comment by KamilSJaron** [comment]
@GLking123 I see, that makes comparison of genomescope and smudgeplot much more difficult. If they are based on the same data, and with the same k, the expected coverage is the same for both methods (and a great deal can be learned when they don't match).

Looking at your plots again I would say the genome does look fairly diploid and very heterozygous - if diploid, I would not be surprised if it was a hybrid species.

What I also did not appreciate before is how many k-mer pairs you actually found - that's an insane number. Perhaps less surprising given the genome size and high heterozygosity, but still... There are so many markers in your genome and vast majority of them are only in diploid state.

If it is actually a tetraploid, I would expect it to be somewhat degenerated tetraploid. If it's a degenerated autotetraploid - there are relatively few k-mers that would be shared in 4 copies compared to those that are in two.

**Comment by GLking123** [comment]
Thank you for your explanation. I will conduct experiments to verify it.
