### ISSUE TITLE
make complete examples

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/smudgeplot#17]
We need some pilot examples that will go from raw reads to smudgeplot. We should do both those that are big and complicated as well as those that are small and simple, I htink three examples will be perfect.

Good candidates for demonstration of power:

- [rainbow trout genome](https://www.nature.com/articles/ncomms4657): it was sequenced by 454, for this reason it would be even more interesting to try it. [Reads](https://www.ncbi.nlm.nih.gov/sra?term=ERP003734)
- [sweet potato](https://www.nature.com/articles/s41477-017-0002-z): hexaploid; [reads](https://www.ncbi.nlm.nih.gov/sra?linkname=bioproject_sra_all&from_uid=301667)
- something small???

**Comment by KamilSJaron** [comment]
- octaploid strawberry: there two sequencing projects, one has it's own nice [webpage](https://www.rosaceae.org/pub/7905), [publication](https://www.ncbi.nlm.nih.gov/pubmed/24282021) and [reads](https://www.ncbi.nlm.nih.gov/sra/DRX012424[accn]). The second one has bit more difficult data, since the coverage is not so high, 2–7× per octoploid chromosome, but maybe thanks to octaploidy one will be still able to see something (like AAAABBBB cluster): [pub](https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.2006062#pbio.2006062.s001)

**Comment by KamilSJaron** [comment]
I was advised to run it on more classical species:
- classical diploid models (Arabidopsis, fly etc)
- tetraploid Xenopus laevis (SAMN04518361) and diploid Xenopus tropicalis or maybe Xenopus borealis (SAMN04518076)

**Comment by KamilSJaron** [comment]
Strawberry tutorial is done here: https://github.com/tbenavi1/smudgeplot/wiki/strawberry-tutorial

Genomescope for determination of L and U:

![plot log](https://user-images.githubusercontent.com/8181573/46479640-cfaaf980-c7ef-11e8-87bf-e205318cd904.png)

![plot](https://user-images.githubusercontent.com/8181573/46479677-e3eef680-c7ef-11e8-8353-28ead5693ab1.png)

![plot](https://user-images.githubusercontent.com/8181573/46483010-ff113480-c7f6-11e8-9455-8f6a720ff72d.png)

These are strawberry smudges:

![f_iinumae_smudgeplot_log10](https://user-images.githubusercontent.com/8181573/46482874-bf4a4d00-c7f6-11e8-920d-7aae44a8db18.png)

![f_ananassa_smudgeplot](https://user-images.githubusercontent.com/8181573/46482986-f0c31880-c7f6-11e8-97f8-535059baa84b.png)

**Comment by rotifergirl** [comment]
Hi Kamil,

I just wanted to check something with my data, so I re-ran the strawberry example using jellyfish (no problems, nearly identical output), and then I downsampled the Fragaria iinumae reads (I took a random 10% of the paired reads, using seqtk). Then I reran the jellyfish and smudgeplot pipeline, and the results certainly reflect what I have seen with my data now too.

It seems to me that a lower coverage results in:
1) slightly worse resolution of smudges (I got the warning "detecting two smudges at the same positions, not enough data for this number of bins lowering number of bins to 	35" with the downsampled reads, but not with the full read library)

2) loss of some smudges, see attached image

![frag50x_genome_smudgeplot_log10](https://user-images.githubusercontent.com/16402395/50844738-ae682500-136b-11e9-8635-91fe02ecdb32.png)


Obviously this is not a fault of the program, but users should be aware of coverage based limitations for this program. 

For my data, my 1n estimates range from 17 to 27.

**Comment by KamilSJaron** [comment]
Hey Julie, the need for coverage is a good point. 

I had troubles to phrase it nicely because it's not that simple. The coverage needed for a nice smudgeplot is dependent on the quality of sequencing (i.e. coverage variance). Smaller variance less coverage is needed to make nice smudges.

I just returned from PopGroup and people are super interested in smudgeplots. I really need to work out better documentation in general. Any input is welcome.

**Comment by KamilSJaron** [comment]
The labeling of octoploid straberry is corrected in 01ddc2e83f9bf3048715b2cea5bad609ac85026b:

![straw_Rver_1 4_smudgeplot](https://user-images.githubusercontent.com/8181573/56972012-8abf2980-6b6a-11e9-9c11-1206aad84ef1.png)

**Comment by KamilSJaron** [comment]
Mountain peanut is a quite nice real-life example of a species that was thought to be hexaploid, but has a kmer data supporting more tetraploidy, discussed in #36

**Comment by KamilSJaron** [comment]
Rainbow trout analyses now available #88

**Comment by OyukaKh** [comment]
Here are the Smudgeplots for S_retusa_T2221 (second example):

![S_retusa_T2221_kmcdb_L54_U400_smudgeplot_smudgeplot_log10](https://github.com/KamilSJaron/smudgeplot/assets/141621511/11594ccb-ad53-42d1-b32b-f467d491e269)
![S_retusa_T2221_kmcdb_L54_U400_smudgeplot_smudgeplot](https://github.com/KamilSJaron/smudgeplot/assets/141621511/5cdb0de3-58a2-4d6a-9e45-1fb73f93d8c1)
