### ISSUE TITLE
Could not successfully run smudgeplot.py plot with the kmer pairs (KMC)

### ISSUE THREAD

**Issue by hungweichen0327** [KamilSJaron/smudgeplot#172]
Dear community,

I used the KMC to calculate the kmer pairs and use smudgeplot to plot the result. However, I got the error. Did I miss the required input data?

version: Running smudgeplot v0.4.0dev

The command I use:

## calculate k-mer freq.
ls *.fastq.gz > FILES
nohup kmc -k25 -t40 -m256 -ci1 -cs10000 @FILES kmcdb tmp > kmc_kmer_freq.log &

## generate histogram
nohup kmc_tools transform kmcdb histogram plant_k25.hist -cx10000 > kmc_histo.log &

## choose coverage threshold
L=$(smudgeplot.py cutoff plant_k25.hist L)
U=$(smudgeplot.py cutoff plant_k25.hist U)
echo $L $U # these need to be sane values

## extract kmers
nohup kmc_tools transform kmcdb -ci"$L" -cx"$U" reduce kmcdb_L"$L"_U"$U" > kmc_transform.log &

## extract Kmer pairs
nohup smudge_pairs kmcdb_L"$L"_U"$U" kmcdb_L"$L"_U"$U"_coverages.tsv kmcdb_L"$L"_U"$U"_pairs.tsv > kmcdb_L"$L"_U"$U"_familysizes.tsv > smudge_pairs.log &

## plot
smudgeplot.py plot kmcdb_L"$L"_U"$U"_coverages.tsv

I got the error:
```
usage: smudgeplot plot [-h] [-o O] [-c C] [-t TITLE] [-ylim YLIM] [-col_ramp COL_RAMP] [--invert_cols] infile smudgefile n
smudgeplot plot: error: the following arguments are required: smudgefile, n
```

The first 5 lines of the file kmcdb_L12_U1100_coverages.tsv is below:
````
21      51
16      29
17      31
13      29
24      28
````

The first 5 lines of the file kmcdb_L12_U1100_pairs.tsv is below:
```
AAAAAAAAAAAAAACAACCGGGTGG       AAAAAAAAAAAAAAAAACCGGGTGG
AAGAAAAAAAAAAAAAACGGTCACC       AAAAAAAAAAAAAAAAACGGTCACC
AAAAAAAAAAAAAAAAAGAGCCGGG       AAAAAAAAAAAAAAGAAGAGCCGGG
CAAAAAAAAAAAAAAAAGGCGGGTC       AAAAAAAAAAAAAAAAAGGCGGGTC
AAAAAAAAAAAAAAAAAGTGAGGTG       AACAAAAAAAAAAAAAAGTGAGGTG
```

The first 5 lines of the file kmcdb_L12_U1100_pairs.tsv is below:
```
29780165
1
2
1
1
```

I would like to ask how to successfully run the smudgeplot.py plot with the input data I had?

Thank you for the kind help.

**Comment by KamilSJaron** [comment]
Hi, the problem is that you run `v0.4.0dev` version of smudgeplot which does not support kmc anymore. You can either install an older version of smudgeplot (e.g. v0.2.5) or you can run the newer version with FastK. I updated the tutorial on the wiki: https://github.com/KamilSJaron/smudgeplot/wiki/BGA24. There are lots of pages on wiki that are outdated (sorry we make lots of changes at the moment)
