### ISSUE TITLE
Histograms missing fromplot

### ISSUE THREAD

**Issue by Artifice120** [KamilSJaron/smudgeplot#174]
**What did you do**

I ran the following bash script.

```
source /lustre/isaac/scratch/jtorre28/enviro/mamba/micro/etc/profile.d/micromamba.sh

micromamba activate smudgy

mer=60

here=/lustre/isaac/scratch/jtorre28/fung-musca-test/

cd $here

FastK -v -T45 -k${mer} -t3 -M1000 -N${here}k-${mer}_13_pandn_table /lustre/isaac/scratch/madler5/pand-reads-11-12/catted_pand.fastq.gz

smudgeplot.py hetmers -L 13  -t 40 -o ${mer}-13-ont-pandn-pairs --verbose k-${mer}_13_pandn_table

smudgeplot.py all -o ${mer}-mer-musca-run ${mer}-13-ont-pandn-pairs_text.smu
```

The plot seems to be missing the edge histograms as well as the prediction text. 

I am not sure if the smudge plot looks this way because of the glitch or the data now.

[60-mer-musca-run_smudgeplot_log10.pdf](https://github.com/user-attachments/files/17778519/60-mer-musca-run_smudgeplot_log10.pdf)

**Comment by KamilSJaron** [comment]
Hi @Artifice120,

given the prediction was never a real inference (it was the ploidy with highest number of k-mer pairs) we decided to temporarily suspend this text - too many people just read that text for poorly looking smudgeplots and think they inferred ploidy. We are working on a model that will make the prediction a bit more sensible and then we will return the label.

The red histograms were hardly ever used feature by anyone, which is also a reason why we did not give it a high priority. But you are not the first one asking for them, so we will be adding them back.

Re your data - I would say it looks like the data is messy. Do you have clear peaks when you run GenomeScope?

**Comment by Artifice120** [comment]
It make sense to remove those two components of the plot. I was just not sure if they were removed on purpose or if it was a result of a missing/malformed dependency.

Genomescope2 infers a peak in the initial error region to the left of the graph at ploidy 2. 

These reads were actually a byproduct of calibrating pacbio equipment with the same sample over a few years was hoping I could at least infer ploidy, look like I will have to wait for actual sequencing to finish.
