### ISSUE TITLE
PloidyPlot: Cannot open k-mer table FastK_Table

### ISSUE THREAD

**Issue by gemmacol** [KamilSJaron/smudgeplot#178]
Hi Kamil! 

Am using FastK and running line by line within the same directory, and have encountered this issue: 

# step one: 
`FastK -v -t4 -k21 -M16 -T4 -P$TMP -c AXG_novaseq_R*.fq -NFastk_Table`

...
_Phase 3 (-t option): Merging K-mer Table Parts

  There are 2,097,969,145 21-mers that occur 4-or-more times

  The table occupies 10.62 GB

  Resources for phase:  1:54.806u  31.215s  1:00.165w  242.7%

Total Resources:  138:34.179u  10:55.452s  57:00.807w  262.2%  14MB_

# step two:
`smudgeplot.py hetmers -L 12 -t 4 -o kmerpairs --verbose FastK_Table`

_Running smudgeplot v0.4.0dev
Task: hetmers
Calling: hetmers (PloidyPlot kmer pair search)  -okmerpairs -e12 -T4 -v FastK_Table
PloidyPlot: Cannot open k-mer table FastK_Table

Done!_

Could it be that the table is too large for smudgeplot.py to open?

**Comment by KamilSJaron** [comment]
UNIXes are case sensitive. In the step one you generated k-mer database called `Fastk_Table` and in the step 2 you tried to get stuff done on `FastK_Table`, which does not exist, `Fastk_Table` does. If you fix that, it should run just fine.

**Comment by KamilSJaron** [comment]
Not really a smudgeplot issue, I will close this issue. If you would have a different problem, feel free to open a new one.
