### ISSUE TITLE
hetkmers.py is computing after it saved coverages_2.tsv file

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/smudgeplot#18]
I made a small trick to avoid the dump file in my computer (I asked kmc to save the output to std out stream and piped it in the hetkmers.py). The log suggest that the job should be finished

![screen shot 2018-10-02 at 09 41 55](https://user-images.githubusercontent.com/8181573/46335425-af304300-c627-11e8-8db5-8397091fd2f9.png)

but it's still actively computing on a single core. This is a htop screenshot:

![screen shot 2018-10-02 at 09 41 23](https://user-images.githubusercontent.com/8181573/46335516-06ceae80-c628-11e8-9802-28cff117ef2f.png)

The output seems correct I managed to create a smudgeplot so I killed, but it's strange no?

**Comment by tbenavi1** [comment]
This is indeed something I have seen before as well. It is odd. Perhaps it is because the code is incorrectly closing either the q queue or the results queue? I will test some changes and update if I can fix it.

**Comment by KamilSJaron** [comment]
I am afraid that the problem still persist, but only for a big file. When I take just the first 1000 lines it works as expected.

![screen shot 2018-10-03 at 11 15 00](https://user-images.githubusercontent.com/8181573/46401555-a316b500-c6fd-11e8-9aa9-9675c8250848.png)

I am not re-opening this issue because I don't have a small reproducible example and because I don't this it's a big issue right now (we have better things to do). I just want to keep a record.

**Comment by tbenavi1** [comment]
I think it is still the hetkmers script because I also got that error with really large files, and I wasn't piping. I still think it has something to do with not correctly closing/joining the queues, but I'm not exactly sure.

**Comment by KamilSJaron** [comment]
Till now I was running smudgeplot on a server therefore I had no problem with manually killing the job. However, now I tried to use our cluster and there it's a pain in the butt because the job just get killed by the time limit which occupies cluster way longer than it should.

I could reproduce this behavior with genome size of 1.3G. But I still don't have a reproducible example. One way to go could be using a debugger for python [pdb](https://docs.python.org/3/library/pdb.html) or alternatively asking on a stack exchange where there are tons of python gurus.

**Comment by KamilSJaron** [comment]
I asked on [Bioinformatics.stackexchange](https://bioinformatics.stackexchange.com/questions/6704/python-does-not-quit-when-the-input-file-is-too-big?noredirect=1#comment9566_6704).

So far they confirmed your suspicion, "this is probably caused by a deadlock in multi-threading." – user172818. Using better keywords I found this [question](https://stackoverflow.com/questions/33825054/deadlock-with-multiprocessing-module) that seems to deal with exactly the same behaviour.

**Comment by KamilSJaron** [comment]
One more comment at the SE question `you probably need to do "from multiprocessing import Pool" and not "Queue" or "spawn"`

**Comment by KamilSJaron** [comment]
I have a suggestion how to resolve this problem.

Let's add a simple test that if user loads more than certain number of kmers, the program quits suggesting to use the fast algorithm discussed #24 (I can check what is the smallest genome when I have encountered this bug)

**Comment by KamilSJaron** [comment]
implicitly resolved by #27. If this problem occurs again, we will reopen this issue.
