### ISSUE TITLE
Preferred citation/DOI request

### ISSUE THREAD

**Issue by rotifergirl** [KamilSJaron/smudgeplot#23]
Hi,

Thanks for the wonderful tool, it's been very useful for my data and I am preparing this data to be submitted as a manuscript soon. I was wondering if you had a preferred citation since smudgeplot is not yet integrated with genomescope or published.

Perhaps you could assign it a DOI with zenodo?

Thanks again!

**Comment by KamilSJaron** [comment]
Hey Julie ^^, indeed this tool has no citation yet. I can take a look how difficult would be to get a Zenodo doi (do you have by any chance an experience with it?). How urgent it is?

**Comment by rotifergirl** [comment]
It's not super urgent, the paper will be submitted in the next weeks, but I believe finalising the citation will only be important after acceptance. 

I don't have experience with Zenodo, but I did find this https://guides.github.com/activities/citable-code/

**Comment by KamilSJaron** [comment]
Good. It seems that getting a DOI is simply matter of filling up an authorship form. Which is great, but I can not do it would discussion with @tbenavi1 (which could happen next week at some point)

I will keep you posted.

**Comment by KamilSJaron** [comment]
I am very excited to announce, that we have an associated DOI: https://www.biorxiv.org/content/10.1101/747568v1
