### ISSUE TITLE
misslabeled smudges

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/smudgeplot#31]
**About your genome**

It's a diploid strawberry, the one that is in the tutorial.

**smudgeplot**

I used the `dev` version of smudgeplot with following command

```
smudgeplot plot -o f_iinumae_2 -t "Fragaria\ iinumae" -nbins 30 -n 144 kmer_pairs_coverages.tsv
```

and the smudgeplots looks like... (the second one is without specification of expected coverage and number of bins)

![f_iinumae_2_smudgeplot_pythonic](https://user-images.githubusercontent.com/8181573/55723349-272d5a80-5a09-11e9-90d0-0f580cc0918e.png)

![f_iinumae_smudgeplot_pythonic](https://user-images.githubusercontent.com/8181573/55723350-272d5a80-5a09-11e9-9aa8-002be890007f.png)

-> it's these AB smudges that make the program think that two smudges are detected at the same place and then reducing the number of bins to ridiculous numbers. It's needed to figure out what is wrong with the python implementation of the fitting algorithm. The R implementation certainly does this fit well.

**Comment by Neato-Nick** [comment]
I think this is the right issue to post under, but I'm not positive.

I used some *Saccharomyces cerevisae* data for testing: Sequencing from a diploid, triploid, and triploid as done in [Knaus et al 2018](https://www.frontiersin.org/articles/10.3389/fgene.2018.00123/full) and [Weiß et al 2018](https://bmcbioinformatics.biomedcentral.com/articles/10.1186/s12859-018-2128-z). They all worked nicely, except for the tetraploid. It's actually a bit odd - the kmer coverage shows the tetraploid smudge (1/4) but  the total coverage of kmer pair isn't correct (4 n). I'm guessing that the smudge at 1/2 x 2n caused the smudge at 1/4 x 2n to be missed? Also, notice that the label it was assigned (AA) is far to the left, not on top of the smudge.

![smudgeplot_smudgeplot](https://user-images.githubusercontent.com/5849554/81441461-ad453480-9126-11ea-8b27-bc1bd70b9069.png)

This is isolate CBS9564, which you can see in the allele spectra below is tetraploid (Fig 1 from knaus et al 2018)
![fgene-09-00123-g001](https://user-images.githubusercontent.com/5849554/81441904-758abc80-9127-11ea-8f88-2d9ac5ff70a4.jpg)

**Comment by KamilSJaron** [comment]
> I think this is the right issue to post under, but I'm not positive.

I encourage people to open new Issues for interpretation problems, but here it's fine too :-)

> sacharomyces

Looking at the smudgeplot you posted - yeah. It's really weird. I am suspecting that the L was too low, but I got to investigate a tiny bit. In matter of fact, I have a small pile of genomes I need to run genome profiling on, I will get to this later next week.

Also, thanks for this! First, I totally wanted to have a sacharomyces example, but I never forced myself to look up the sequences with different ploidy levels. Would you mind If I turned them in a tutorial?

**Comment by KamilSJaron** [comment]
> re labeling

The "AA" smudge is misplaced, because smudgeplot knows that 2n smudges can be only AB or AA and the label is then rounded to 0.5. AA means that the actual coverage ratio was closer to 0 than to 0 (which is obviously a very suspicious smudge in first place, even its mere existence should make us wonder what has happened). The algorithm rounds to x / possible_number_of_genomic_copies for x in 0 ... possible_number_of_genomic_copies.

**Comment by Neato-Nick** [comment]
> Would you mind If I turned them in a tutorial?

Totally! It's a really nice dataset. For the most part they turned out well. The coolest one to me was a mostly diploid isolate with one triploid chromosome (YJM1098). This shows up perfectly in the smudgeplot

![smudgeplot_smudgeplot](https://user-images.githubusercontent.com/5849554/81481929-51db7b00-91e8-11ea-8fe6-25db5ed50147.png)

**Comment by KamilSJaron** [comment]
I moved the issue to #53, because I got plenty of figures I need to upload and I don't want to post to a thread about something else.
