### ISSUE TITLE
Smudgeplot interpretation

### ISSUE THREAD

**Issue by Ram-Nagar** [KamilSJaron/smudgeplot#35]
Hi Kamil, 
I am using smudgeplot to look at the state of ploidy in a plant pathogenic fungs. I counted kmer coverages with KMC and then plotted with smudgeplot as instrected in the tutorial. The fungs is a diploid/dikaryon (two haploid genome in two nuclei) which what I see with most of the isolates I tested with smudgeplot but interestingly one isolate was estimated to be tetraploid!
I still not sure how smudgeplot estimated ploidy by counting the pair of heterozygous k-mers, so could you please have a look at the plot and help me to understand what is going on.
![PST_S00832A_smudgeplot](https://user-images.githubusercontent.com/18412525/57675473-7b110c00-7665-11e9-9ecf-a6944756a1d0.png).

Also, most of the fungs isolate estimated to be diploid with one smudge, but I see one with two smudges, so wondering how do I  interpret the number of the smudges in the plot. 
Look at the plots here:
![PST_DK09_smudgeplot](https://user-images.githubusercontent.com/18412525/57675962-b9f39180-7666-11e9-8729-a24e666e5d58.png)
![ERR1607728_smudgeplot](https://user-images.githubusercontent.com/18412525/57675981-c8da4400-7666-11e9-83ac-5a03cf82752a.png)

The size of the genome is estimated to be ~80-90 mb but no information about the number of chromosomes is known.

Thanks
Ram

**Comment by KamilSJaron** [comment]
Hi Ram,

on the first glance, I would say that ERR1607728 and S00832A are tetraploids and DK09 is a diploid.

[Heterozygous kmer pairs](https://github.com/KamilSJaron/smudgeplot/wiki/FAQ#1-what-are-heterozygous-kmers-are-these-kmer-pairs-with-a-close-but-not-perfect-sequence-match) are nothing else than just pairs of kmers that are very similar and form a unique pair. Smudgeplot use the "least covered" smudge to estimate 1n coverage and then 1n coverage estimate to label all the smudges. If 1n est is correct, then ERR1607728 and S00832A have most of their closely related kmers in 4 genomic copies.

I see that ERR1607728 is estimated diploid, but I think what is labeled as AAABB should be a part of AABB. I think this smudgeplot would benefit from lower nbins (25, maybe 30 would do the job).

Finally, have you tried to run genomescope? Sometimes genomes with very little heterozygosity and frequent duplication can appear to be tetraploid. Check [strawberries](https://github.com/KamilSJaron/smudgeplot/wiki/strawberry-tutorial) for instance.

**Comment by KamilSJaron** [comment]
closing for now. If you still got a problem, don't hesitate to reopen this issue.
