### ISSUE TITLE
install smudgeplot on cluster

### ISSUE THREAD

**Issue by jblamyatifremer** [KamilSJaron/smudgeplot#41]
Dear Smudgeplot creator, 
I am able to install without any problem smudgeplot on a local pc and I also success to create a conda env able to run smudgeplot, but i got an error because my "smudgeplot and smudgeplot_plot.R" are not in /usr/local/bin...

**Comment by KamilSJaron** [comment]
Everything sorted? :-)

**Comment by jblamyatifremer** [comment]
No... 
I was trying something... but it is not working.
 
A simple trick would to have the possibility to pass to smudgeplot an alternative path for smudgeplot.py and smudgeplot_plot.R. 
I tried to add my custom path straigth into smudgeplot.py (line) myself but without success. I do not have an overall view of the code.

Any idea ? 
JB

**Comment by KamilSJaron** [comment]
I think the only thing you need is to export the PATH that includes path to the smudgeplot scripts.

Did you try what is suggested [here](https://github.com/KamilSJaron/smudgeplot/wiki/installation#localcluster-installation)?

**Comment by jblamyatifremer** [comment]
Thank you... It works... but now I have new errors than i need to understand... I will keep you in touch. 
JB

**Comment by KamilSJaron** [comment]
Practically, there can be only two possible problems. Missing R libraries, or missing python libraries. If all that is in place, the scripts got to work. Good luck.

**Comment by jblamyatifremer** [comment]
To keep you in touch.
I am able to run smudgeplot on my local pc on a subset of the kmer_counts.trim.jf with any problem... But I still have some problems with my custom install on cluster (Bus error). 
I will contact my IT and send to him this threads, i suspect problem on the cluster side rather than smudgeplot.
Cheers, JB
