### ISSUE TITLE
smudgeplot.py hetkmers keeps on failing

### ISSUE THREAD

**Issue by Malabady** [KamilSJaron/smudgeplot#44]
Hi there:

I trying to run "smudgeplot" on kmc-generated kmers (22) from pacbio data of a 3.6g genome.

Here are my commands:

```
smudgeplot.py hetkmers -o kmer_pairs kmer_k22_ci30cx1500.dump
smudgeplot.py plot -o S_purpurea -t "S. purpurea" -q 0.99 kmer_pairs_coverages.tsv
```

after an hour of running, the job gets killed and I get this message: 

```
/var/spool/torque/mom_priv/jobs/1529182.sapelo2.SC: line 20: 47649 Killed                  smudgeplot.py hetkmers -o kmer_pairs kmer_k22_ci30cx1500.dump
```

I am running it on a single node with 850gb of RAM allocation. 

The dump file is ~ 33Gb and has over 1.3b lines. by multiply the number of kmers in the dump file by 350,  roughly about 600Gb are needed for the job. But it still fails with 850Gb. 

Any suggestions or guidance are highly appreciated.

Many thanks,
Magdy

**Comment by KamilSJaron** [comment]
Hi Magdy, thanks for trying out Smudgeplot.

The tool is mainly aiming for short-read data. In theory, it could work for long reads too, but it would require a lot of coverage. How much data you have for the 3.6g genome? Also, do you have a kmer histogram? That could give you an idea if running smudgpelot will yield in something meaningful.

Finally, I am moving between countries this month, sorry if my responses are delayed.

Best,
Kamil

**Comment by KamilSJaron** [comment]
Hello Magdy, I will close this issue for now as I don't see a way how to help you.

If you would get back to Smudgeplot, please feel free to post here again and I will reopen the issue for you.

**Comment by raplayer** [comment]
Hello, similar issue, but using Illumina read set (107GB fastq, 14GB dump file), and am getting this when running hetkmers:
`Running smudgeplot v0.2.3dev`
`Task: hetkmers`
`Killed`

Killed occurs when mem usage gets to ~60GB, on a 500GB RAM system.

Any suggestions much appreciated,
Thanks!

**Comment by KamilSJaron** [comment]
Hi @raplayer, are you sure that is not a some sort of a watchdog on that server that is killing to process? You could also try the kmc version of kmer pairs that uses much less memory than the python version.

Also, thanks for reading through issues before opening one :-)

**Comment by raplayer** [comment]
lol, np Kamil, thanks for the quick response!

Definitely not a watchdog killer, will try the KMC version and report back if still having issues.

**Comment by KamilSJaron** [comment]
Hmm, strange. I certainly run this script with ~600G memory (when I did a smudgeplot of a crayfish). Not sure what can kill your process. Hopefully, the KMC version will solve it.
