### ISSUE TITLE
question about smudgeplot_plot.R

### ISSUE THREAD

**Issue by xiehuanhuan2018** [KamilSJaron/smudgeplot#51]
![image](https://user-images.githubusercontent.com/43092469/78089261-737f6080-73f9-11ea-8fc0-5379f156bcd3.png)
Hi, when I run smudgeplot, 'smudgeplot.py plot ' occurs error, showing: smudgeplot_plot.R command not found. How can I deal with it? Thank you.

**Comment by KamilSJaron** [comment]
Hello, that sounds like the script `smudgeplot_plot.R` was not installed properly. Could you please prove me with commands you use to install smudgeplot?

**Comment by KamilSJaron** [comment]
Alright, a tiny longer answer.

There are three components of the current version of smudgeplot: an R package called smudgeplot, a script  `smudgeplot_plot.R` for the R part, and `smudgeplot.py`, which contain all the python code. 

Installing smudgeplot is practically 1. installing the R package and 2. copying those two scripts somewhere, where your systems see them (one of the directories mentioned in $PATH). All this should be handled by conda (including python and R dependencies), othervise you need to follow the instructions [at our wiki](https://github.com/KamilSJaron/smudgeplot/wiki/installation)

I quite sure that this is not a problem of smudgeplot, therefore I close this issue for now. If you would have more problems, don't hesitate to reopen it again.

**Comment by xiehuanhuan2018** [comment]
Thank you very much for your patient answer.I have fixed the problem. In addition, I'm sorry for a late reply. Thanks again.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Kamil S. Jaron"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月2日(星期四) 晚上6:48
收件人:&nbsp;"KamilSJaron/smudgeplot"<smudgeplot@noreply.github.com&gt;;
抄送:&nbsp;"向日葵"<1531123273@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [KamilSJaron/smudgeplot] question about smudgeplot_plot.R (#51)





 
Alright, a tiny longer answer.
 
There are three components of the current version of smudgeplot: an R package called smudgeplot, a script  smudgeplot_plot.R for the R part, and smudgeplot.py, which contain all the python code.
 
Installing smudgeplot is practically 1. installing the R package and 2. copying those two scripts somewhere, where your systems see them (one of the directories mentioned in $PATH). All this should be handled by conda (including python and R dependencies), othervise you need to follow the instructions at our wiki
 
I quite sure that this is not a problem of smudgeplot, therefore I close this issue for now. If you would have more problems, don't hesitate to reopen it again.
