### ISSUE TITLE
Wrong result of Salix

### ISSUE THREAD

**Issue by BeardLi** [KamilSJaron/smudgeplot#52]
Hi,
   
I ran into some problems when I do smudgeplot with Salix data.
Here is my reslut:
![ljs_smudgeplot](https://user-images.githubusercontent.com/65237065/82013656-623e9a80-96ad-11ea-85fe-969cd6169c2f.png)
![ljs_smudgeplot_log10](https://user-images.githubusercontent.com/65237065/82013666-67034e80-96ad-11ea-9269-9564b95f1819.png)

My L and U is determined after I ran genomescope:
![plot](https://user-images.githubusercontent.com/65237065/82013780-b0ec3480-96ad-11ea-8bfa-f442f7be35b3.png)

I'm confused because this picutre says that my reads' coverage is only ~7, which actually should be ~18

Afterall, accroding to this picture, my L is 7. And I have a terrible result.
The thing I want to know is: Is there anything wrong with my reads data? Or something wrong with other part?

Thanks for your program.

**Comment by KamilSJaron** [comment]
Hi there,

Regarding 7.3x or 18x. 7.3 is an estimate of monoploid coverage (how many times every haplotype was covered), while I expect 18x was your estimate of 2n coverage (how many times every site in the genome was covered regardless from which haplotype the reads comes). So, it seems that the kmers still predict a smaller coverage (~15x), but it's nothing as dramatic as 7 vs 18.

And regarding the noisy smudgeplot. The thing is you have very very low coverage, from [the documentation](https://github.com/KamilSJaron/smudgeplot/wiki/everything-about-input-data):

> To sum up, if you have >100x per haplotype, the smudgeplot should be really nice. If you have nice libraries and >25x per haplotype, the smudgeplot should be really nice. If you have less than that or there is something else going on (like whole genome amplification), smudgeplot probably won't be very informative.

The smudgeplot looks often quite weird when the coverage is so low that haploid and error kmers are impossible to separate.

As a conclusion, there is nothing wrong with your data besides being really low coverage. My best guess is that it's a diploid, looking just at the GenomeScope (I don't think you really need a smudgeplot here, it's a clear cut). Hope this helps :-)

**Comment by BeardLi** [comment]
Hi,
Thank you very much for your help! Indeed, all my datas' coverage are between 16x-26x. Obviously not enough for the smudgeplot.
Thank you again for your cool program and patience!!!

**Comment by KamilSJaron** [comment]
With pleasure.

Hope you'll find at least the genome scope informative (that seems to me that that worked quite nice). CLosing the issue for now, but feel free to reopen if something...

**Comment by KamilSJaron** [comment]
@BeardLi We just got a Salix in the Tree of Life that has nearly identical looking profile BUT it's very clearly a tetraploid with very low heterozygosity (so the two visible peaks are 2n and 4n). Not sure if still helpful, but here goes nothing.
