### ISSUE TITLE
strange sacharomyces smudgpelot

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/smudgeplot#53]
**About your genome**

Saccharomyces, 12M monoploid genome size.

**smudgeplot**

Described [here](https://github.com/KamilSJaron/smudgeplot/issues/31#issuecomment-625979647).

Long story short, what should have been a tetraploid smudgeplot looks like this:

![wrong_smudgeplot](
https://user-images.githubusercontent.com/5849554/81446487-d5856100-912f-11ea-9b51-efb907a3f04e.png).

**Comment by KamilSJaron** [comment]
So I looked at the kmer histogram (fitted there diploid model for no particular reason):

![Scer_genomescope_plot](https://user-images.githubusercontent.com/8181573/82441921-a0193580-9a96-11ea-8719-a891a35ac230.png)

And I wonder. Is the ~15x peak a haploid peak or something else? I can not tell if it's precisely 1/4 of the big peak.

So I suppose I will be able to recunstruct your smudgeplot by selecting L=15. And indeed:

![sacharomyces_L15_smudgeplot](https://user-images.githubusercontent.com/8181573/82442136-fa19fb00-9a96-11ea-90c3-b11053108257.png)

(non log scale, but the same principle). Which is quite funny. It seems that the kmers from 15x peak pair up ~ with the 45x peak (that's the left most smudge), there are a bunch of ~30x peak that pair up with ~30 (that's the AB smudge), but there are no kmers from the 15x peak that would pair with itself. Which is rather intriguing.

Alternatively, the 15x peak is a contamination of some sorts and removing it from the smudgeplot would increase the clarity, but that looks like this:

![sacharomyces_L30_smudgeplot_log10](https://user-images.githubusercontent.com/8181573/82442551-cab7be00-9a97-11ea-9de5-c6452e4ffcf6.png)

I guess not really the case, especially as we kind of know it's tetraploid. So, we can try to fit there a tetraploid model of genomescope:

![Scer_genomescope_p4_plot](https://user-images.githubusercontent.com/8181573/82442622-ee7b0400-9a97-11ea-8a22-c1990e7348ce.png)

it does fit reasonably well. So, if we rerun smudgeplot with genomescope estimate of 1n coverage (17x), we get a smudgeplot that seems to be correctly labeled and predict the ploidy as expected:

![sacharomyces_L15_n17_smudgeplot](https://user-images.githubusercontent.com/8181573/82443054-bf18c700-9a98-11ea-8d6b-e23cb700510f.png)

I do admit though, that this was again a tough cookie.

**Comment by Neato-Nick** [comment]
Whoa! Neat! Interesting that changing L from 15 to 17 fixed the problem (am I reading that correctly?)

So in sum: Genomescope's error overlapping with that first defined peak is a clue that something is wrong. Re-running the model as tetraploid is a better fit, and the output summary indicates a 1n coverage of 17x, which is how you decided to try L=17 in smudgeplot instead of the L=15 suggestion from `cutoff`?
So, how might you decide on a ploidy level for genomescope without knowing the ploidy a priori? Maybe just trying different copy number levels in genomescope until you get the best fit?

**Comment by KamilSJaron** [comment]
I was a bit sloppy over here, mostly because I was just posting figures for this tutorial: https://github.com/KamilSJaron/smudgeplot/wiki/tutorial-saccharomyces

The L has not changed at all. I used L = 15, but instead of letting smudgeplot estimate the 1n coverage (it thought it's ~35x) I told it that it's just 17x. Once smudgeplot had the prior, it could correctly assign labels to the smudges (AB -> AABB and AA -> AAAB). 

Otherwise you are right, looking at the genomescope, I knew I need to figure out if the ~15x peak is part of the genome or not. Then I compared the histogram and smudgeplot and thought which kmer pairs would generate the smudges I see and realized it must be 15 <-> 45 and 30 <-> 30 and that there are no 15 <-> 15 ones which is the reason why smudgeplot got confused a bit.

Does it make more sense now? If it does, would you mind taking a look at the tutorial and let me know if it's understanble there as well, or if I should make some changes. Or even better, if you would suggest the changes :-)

**Comment by Neato-Nick** [comment]
Cool! I'm quickly going through it now and will work through it this week. Couple questions already

#### intro

> Beside the AB smudge, there is also a one more ~ at the L * cov line (the error line)

Does this refer to the AABB smudge or the AA smudge? Also, how can I tell where the error line is?

#### analysis

> The 2n estimate is ~35x (but looking the smudge behind the annotation, it seems it's slightly less).

Is "2n" supposed to read "1n"? Next to the y-margin-histogram in the smudgeplot above this paragraph, the text reads "1n = 35"

> Interesting enough, there is no smudge ~30x, where one would expect one made of kmer pairs between 1n peak, which is the main reason why the smudgeplot was confused with the annotation of smudges. 

This sentence confuses me. Maybe I just haven't looked at enough smudegplots to be able to "see" a smudge as a precise X coverage? I also don't think I follow why I would expect a smudge of kmer pairs between 1n peaks.

Overall, the walkthrough is great! It is really helping me understand how to iterate the process to more correctly infer ploidy

**Comment by KamilSJaron** [comment]
>      Does this refer to the AABB smudge or the AA smudge? Also, how can I tell where the error line is?

Actually, I meant the unlabelled yellow smudge right in between of AA and AB smudge labels.

> Is "2n" supposed to read "1n"? Next to the y-margin-histogram in the smudgeplot above this paragraph, the text reads "1n = 35"

yeah.

>  This sentence confuses me. Maybe I just haven't looked at enough smudegplots to be able to "see" a smudge as a precise X coverage? I also don't think I follow why I would expect a smudge of kmer pairs between 1n peaks.

I used ~ to say "approximately (you expect the brightest spot to be approximately at 30x)". I was a bit more verbose now

Alright, what is going on? The 1n estimate is ~35x (but looking the smudge behind the annotation, it seems it's slightly less). Therefore the AA and AB smudges are (a bit less than) ~70x. Hence they probably correspond to pairing of 15x peak with 45x peak in the AA case and kmers from 30x peak with itself. Interesting enough, there is no smudge around 30x, where one would expect one made of kmer pairs within 1n peak. The absence of pairs within the 1n peak is actually the main reason why the smudgeplot was confused with the annotation of smudges.

**Comment by KamilSJaron** [comment]
I just found that there are plenty of issues I forgot to reply to (this one included, and I am sorry about that).

I will close this to make it cleaner here, but if anything, feel free to reopen.
