### ISSUE TITLE
memory insufficient

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [KamilSJaron/smudgeplot#56]
HI Kamil,
I tried to run smudgeplot.py with the hetmer option to extract heterozygous Kmers using ~60Gbp human HIFI data on a 1T RAM node. The sorted kmer dump file is 51G, and the script failed to generate any output kmer pairs because of insufficient RAM.
Do you plan to further develop this part of the script to make it be compatible with super giant dataset?
Thanks much,
Best,
Zhenzhen

**Comment by tbenavi1** [comment]
Hello Zhenzhen,

We recommend using the smudge_pairs script from https://github.com/tbenavi1/KMC to account for giant datasets. I spoke with you earlier today to help you install it. Please let me know if you have any questions. The instructions to run the tool are in the readme for Smudgeplot.

**Comment by zhenzhenyang-psu** [comment]
Hi Timothy,
Thanks very much for pointing it out, this is exactly what I need. 
I found this where mentioned how to use smudgepairs script:

kmc -k21 -t16 -m64 -ci1 -cs10000 @FILES kmcdb tmp
kmc_tools transform kmcdb -ci$L -cx$U reduce kmcdb_L$L\_U$U
smudge_pairs kmcdb_L$L\_U$U kmcdb_L$L\_U$U_coverages.tsv kmcdb_L$L\_U$U_pairs.tsv > kmcdb_L$L\_U$U_familysizes.tsv
"kmcdb is the output file name prefix for the KMC database"

Do you think your smudgepairs program could be used on jellyfish output? The issue that I had is that KMC cannot generate a kmcdb database with HIFI data as input, which is what I am trying to get hetkmers from.

Is "kmcdb_L$L\_U$U" the only input of your smudgepairs script?
If you can provide some thoughts or opinions on this, that would be great!

Zhenzhen

**Comment by tbenavi1** [comment]
KMC should be able to generate a kmcdb database with HIFI data as input. What problems are you running into? Also, at the moment smudge_pairs cannot run on jellyfish output.

**Comment by zhenzhenyang-psu** [comment]
very interesting! I used the previous precompiled binary KMC UNIX version which failed on HIFI data.
I just tested with the compiled kmc version, it worked! thanks a lot! 
Zhenzhen

**Comment by KamilSJaron** [comment]
It seems that this problem is resolved (Thanks @tbenavi1!).

I'll close it for now, if anything, don't hasitate to reopen it.

**Comment by zhenzhenyang-psu** [comment]
sure! thanks!
