### ISSUE TITLE
use of '-cs10000' - maximal value of a counter?

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [KamilSJaron/smudgeplot#57]
Hello there,
I have a hard time understanding the use of '-cs10000' in the following code in the README:
# kmer 21, 16 threads, 64G of memory, counting kmer coverages between 1 and 10000x
kmc -k21 -t16 -m64 -ci1 -cs10000 @FILES kmcdb tmp
kmc_tools transform kmcdb histogram kmcdb_k21.hist -cx10000

In lmc, the '-cs' is defined as 'maximal value of a counter', do you know what it means? Why do you use -cs10000, or do you attempt to use -cx10000?

thanks much,
Zhenzhen

**Comment by tbenavi1** [comment]
As I understand it, '-cs' is internally used to decide how many bytes are required to store the counter of a k-mer. For example, if there is a kmer that occurs 1000 times in the sequencing data, but '-cs' is set to 255, then the stored value of the counter will be 255 and not 1000. On the other hand, '-cx500' for example will exclude kmers whose counter is greater than 500. So, '-cs' is a parameter that determines the largest value of the counter for each kmer, and '-cx' is a parameter which tells us which set of kmers we are considering. I hope that makes sense. 

Take a look at https://github.com/refresh-bio/KMC/issues/136 for more information.

**Comment by zhenzhenyang-psu** [comment]
got it, thanks very much! My understanding that using default should be able to handle almost all the cases. CS default is 255 which should handle Kmer counts that are 2^255, so I don't think this will affect kmers that are filtered. 
But '-cs1000' somehow is confusing to me, does this mean that numbers that take larger than 1000 bytes will be treated as using 1000 bytes? In theory this would only have a difference if the count is 2^1000, which is almost never going to happen.

thanks,
Zhenzhen

**Comment by tbenavi1** [comment]
Actually, the CS default of 255 handles kmer counts that are up to 255 (only one byte is set internally). Depending on the genome and the downstream application, I may recommend setting CS up to 10 million (for example, if you are trying to get an accurate estimate of genome size for an extremely large or repetitive genome).

**Comment by zhenzhenyang-psu** [comment]
got it! thanks for the explanation!

**Comment by KamilSJaron** [comment]
This is long-time resolved, right?
