### ISSUE TITLE
heterozygous kmer extraction from smudges

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [KamilSJaron/smudgeplot#58]
Hi Kamil,
Thanks for developing such a useful tool!  I think it's amazing.
I had a question on how to separate Kmer pairs based on the smudges inferred from the smudgeplot.
I was using the yeast tutorial to learn how this works, and the command to generate the smudgeplot is:
~/tools_zz/smudgeplot/bin/smudgeplot.py plot kmcdb_L10_U2000_coverages.tsv
And it generated output like this:
* Proportion of heterozygosity carried by paralogs:	0.027
* Summary of all detected peaks (table)
   peak kmers [#] kmers [proportion] summit B / (A + B) summit A + B
1    AA    717175               0.64               0.24        65.47
2    AB    376269               0.33               0.49        65.47
3 AAABB     30112               0.03               0.49       148.08

I am actually interested in separating or extracting Kmer pairs that come from the 'AB' peaks. The smudge_pairs script was able to generate heterozygous kmer pairs that differ at any position. The pair sequences were exported in file: kmcdb_L10_U2000_pairs.tsv, for instance.

 My understanding is that AB represents kmer pairs from  heterozygous regions of the genome. So if I wanted to extract pairs just from this smudge, is there a way to do that?
I saw that you call "extraction of smudges" done in an earlier post:
https://github.com/KamilSJaron/smudgeplot/issues/6 

Just curious if there is a way to extract kmer pairs from these different smudges out of the pairs 'kmcdb_L10_U2000_pairs.tsv' for instance.

thanks much!
Zhenzhen

**Comment by KamilSJaron** [comment]
Hi Zhenzhen, I see that you have really done a deep dive in Smudgeplot, thanks and welcome to the world of kmer pairs.

Regarding the automated extraction algorithm. I indeed planned to make it a core function, and I when I tried to reimplement everything in python. The that version of smudgeplot I actually managed to finish the kmer extraction method, but some other stuff did not work so we are still in the R/python/C++ mess.  Long story short - the production-ready smudgeplot does not have this functionality yet. 

To extract kmer pairs of different smudges I think the easiest will be to use the KMC-based kmer pair extraction that outputs both kmer pairs and their corresponding coverages. From the smudgeplot you can define the coverage boundaries and then get them out using a custom script.

**Comment by zhenzhenyang-psu** [comment]
thanks very much, Kamil.
I figured that one would use the coverage and B/A+B ratio cutoffs to group those kmer pairs.
Let me look into the R code to see how to extract it.
appreciate your reply.
zhenzhen

________________________________

**Comment by KamilSJaron** [comment]
Excellent. As a matter of fact, if you are willing to write and share a script that extracts kmer pairs in a coverage sum and a minor coverage ratio defined by user, I'd be happy to integrate it in the smudgeplot toolkit.

The script can be either in R, or python. Then we can call it externally from the smudgeplot main script (I am happy to do this part). At the end, it could be something like

```
smudgeplot.py extract <coverage_file> <kmer_file> <from_sum> <to_sum> <from_ratio> <to_ratio>
```

Would you be keen to contribute / do a pull request?

**Comment by zhenzhenyang-psu** [comment]
sure! It sounds like not a difficult thing to do:)

**Comment by zhenzhenyang-psu** [comment]
Hi Kamil,
Here is a simple python script that can do the extraction. Not exactly what you want but hopefully can do the job.
https://s3.wasabisys.com/aiden-zhenzhen/public/temp/extract_kmer_pairs_based_on_kmer_sum_and_ratio_zz.py
thanks,
zhenzhen

**Comment by KamilSJaron** [comment]
That's really cool Zhenzhen, there are just a few adjustments I would propose. 

Would you like to do a pull request so I can comment directly the code?

**Comment by zhenzhenyang-psu** [comment]
Hi Kamil,
I created one pull request (https://github.com/KamilSJaron/smudgeplot/pull/59). 
Yet I am not sure if I did it correctly :D, forgive me for being a relatively new user of github.
thanks,
zhenzhen

**Comment by KamilSJaron** [comment]
Hello Zhenzhen, the pull request looks alright. I will need just some minor styling adjustments, but this was already a great help - thanks for the contribution.

I have a few deadlines this week, that's why I did not manage to get through it yet. Just writing to let you know that I did not forget about it :-).

**Comment by zhenzhenyang-psu** [comment]
sounds good:). thanks for letting me know the pull request was successful.

**Comment by zhenzhenyang-psu** [comment]
Hi Kamil,
Hope all is well.
I wanted to ask you how you defined the coverage and ratio cutoffs from the smudgeplot.
I have a test dataset (https://s3.wasabisys.com/aiden-zhenzhen/public/temp/temp_smudgeplot_Help/zhenzhen_coverages.tsv), with which I ran smudgeplot. I tried to extract the pairs that correspond to the "AB" smudge. I know the ratio cutoff for AB is 0.48, but I wonder how total coverages for these AB smudge are determined. The smudgeplot_plot.R script uses a subscript "estimate_1n_coverage_1d_subsets.R" which returns the "1n_coverage" of 11.1.

I tried to use the "smudge_container" to generate cutoffs, however I found the numbers returned are unexpected.

I printed out some relevant variables just to see if some of them are useful:

[1] "smudge_contain is"
$x
 [1] 0.000 0.025 0.050 0.075 0.100 0.125 0.150 0.175 0.200 0.225 0.250 0.275
[13] 0.300 0.325 0.350 0.375 0.400 0.425 0.450 0.475

$y
 [1]  19.00  23.55  28.10  32.65  37.20  41.75  46.30  50.85  55.40  59.95
[11]  64.50  69.05  73.60  78.15  82.70  87.25  91.80  96.35 100.90 105.45

[1] "peak_sizes is: "
   peak abs_size   rel_size  vals  x  y summit minor_variant_cov pair_cov
1     1   219787 0.44260407 93935 20  1   TRUE            0.4875   21.275
2     2    96007 0.19333759 16817 19  4   TRUE            0.4625   34.925
6     6    36636 0.07377708  3574 11 10   TRUE            0.2625   62.225
4     4    35319 0.07112492  4082 14  8   TRUE            0.3375   53.125
3     3    22937 0.04619022  5753 14  6   TRUE            0.3375   44.025
8     9    19703 0.03967763  2411  9 13   TRUE            0.2125   75.875
7     8    19426 0.03911981  2707  9 10   TRUE            0.2125   62.225
10   11    17660 0.03556347  2064  9 15   TRUE            0.2125   84.975
5     5    17647 0.03553729  4031 11  8   TRUE            0.2625   53.125
9    10    11455 0.02306792  2271 11 13   TRUE            0.2625   75.875
   minor_variant_cov_rounded structure corrected_minor_variant_cov ploidy
1                       0.50        AB                        0.50      2
2                       0.50       AAB                        0.33      3
6                       0.25    AAAABB                        0.33      6
4                       0.33     AAABB                        0.40      5
3                       0.33      AAAB                        0.25      4
8                       0.20   AAAAAAB                        0.14      7
7                       0.20    AAAAAB                        0.17      6
10                      0.20  AAAAAABB                        0.25      8
5                       0.25     AAAAB                        0.20      5
9                       0.25   AAAAABB                        0.29      7
[1] "smudge_summary is: "
$n_subset_est
[1] 11.1

$n_peak_est
[1] 9.969065

$n
[1] 11.1

$peak_sizes
   peak abs_size   rel_size  vals  x  y summit minor_variant_cov pair_cov
1     1   219787 0.44260407 93935 20  1   TRUE            0.4875   21.275
2     2    96007 0.19333759 16817 19  4   TRUE            0.4625   34.925
6     6    36636 0.07377708  3574 11 10   TRUE            0.2625   62.225
4     4    35319 0.07112492  4082 14  8   TRUE            0.3375   53.125
3     3    22937 0.04619022  5753 14  6   TRUE            0.3375   44.025
8     9    19703 0.03967763  2411  9 13   TRUE            0.2125   75.875
7     8    19426 0.03911981  2707  9 10   TRUE            0.2125   62.225
10   11    17660 0.03556347  2064  9 15   TRUE            0.2125   84.975
5     5    17647 0.03553729  4031 11  8   TRUE            0.2625   53.125
9    10    11455 0.02306792  2271 11 13   TRUE            0.2625   75.875
   minor_variant_cov_rounded structure corrected_minor_variant_cov ploidy
1                       0.50        AB                        0.50      2
2                       0.50       AAB                        0.33      3
6                       0.25    AAAABB                        0.33      6
4                       0.33     AAABB                        0.40      5
3                       0.33      AAAB                        0.25      4
8                       0.20   AAAAAAB                        0.14      7
7                       0.20    AAAAAB                        0.17      6
10                      0.20  AAAAAABB                        0.25      8
5                       0.25     AAAAB                        0.20      5
9                       0.25   AAAAABB                        0.29      7

$genome_ploidy
[1] 2


Here is the smudgeplot: https://s3.wasabisys.com/aiden-zhenzhen/public/temp/temp_smudgeplot_Help/smudgeplot_smudgeplot_log10.png

As you can see, the AB smudge contains 44% (93935) of all the pairs. Could you perhaps tell me the actual cutoffs used in defining these 44%?

The command I used is: 
conda activate smudgeplot
 Rscript smudgeplot_plot.R -i zhenzhen_coverages.tsv -k 91

Really appreciate it!
Best,
Zhenzhen

**Comment by KamilSJaron** [comment]
Hi Zhenzhen, I am glad you are having fun with smudgeplot :-).

The smudgpelot you linked does not seem to carry clear signal, it's all kind of one huge smudge, there is just so much the algorithm can do with this data. You could try to clean up the data somehow, but my best guess is that the coverage is insufficient. If I recall right, the other day you posted a smudgeplot that looked much better. I think the method for extraction of kmers will be useful only for these "obvious" cases. Unfortunately, the requirement of clean data for smudgeplot is rather strict.

Regarding your questions about 1n estimates: There are two techniques to estimate 1n coverage, all the annotated peaks are just multiplications of that estimated (i.e. even spacing of labels is guaranteed by the algorithm). The subset technique is documented [here](https://github.com/KamilSJaron/smudgeplot/wiki/1n-estimation:-subsets) the other one I call the highest peak estimate is documented [here](https://github.com/KamilSJaron/smudgeplot/wiki/estimate-from-the-highest-peak
) - this one aims for more precise estimate of the coverage, but sometimes is terribly wrong, therefore we accept that one only if it's similar to the subset estimate. If the documentations won't be enough, you need to look at the code (which you already do). Smudgeplot is built as a an R package. I was not trying to be very smart when I was building it, it's simply a bunch of consecutively called functions wrapped in a package just for convenience. The invidual functions are here: https://github.com/KamilSJaron/smudgeplot/tree/master/R. If you would really get into it, the wiki contains quite a lot of information (there are 17 crosslinked pages of documentation).

Hope this helps.

K

**Comment by KamilSJaron** [comment]
Uh, and the outer boundary of the smudges (tiles around the peak) are defined using local aggregation. On [this line](https://github.com/KamilSJaron/smudgeplot/blob/master/exec/smudgeplot_plot.R#L83) I call (peak_agregation.R)[https://github.com/KamilSJaron/smudgeplot/blob/master/R/peak_agregation.R] function to aggregate tiles around the local maximas, allways assigning tile to agregation of the tile with the most kmer pairs around.

**Comment by KamilSJaron** [comment]
I guess it would be possible to generate one more data frame and output file with boundaries of all tiles and their respective smudge assignment (this was actually planned, but we never implemented it). This file could be then used by the "cutting" algorithm to generate corresponding smudge kmer pair files.

**Comment by zhenzhenyang-psu** [comment]
Hi Kamil,
Thanks for your detailed reply.
Is $smudge_contain (see below) the dataframe with the boundaries? 
$x appear to be the left boundaries of all the bins for the minor allele ratio and $y are the bin boundaries for the total_cov. Could you briefly explain how many squares you assign to the AB smudge? (https://s3.wasabisys.com/aiden-zhenzhen/public/temp/temp_smudgeplot_Help/smudgeplot_smudgeplot_log10.png)

[1] "smudge_contain is"
$x
[1] 0.000 0.025 0.050 0.075 0.100 0.125 0.150 0.175 0.200 0.225 0.250 0.275
[13] 0.300 0.325 0.350 0.375 0.400 0.425 0.450 0.475

$y
[1] 19.00 23.55 28.10 32.65 37.20 41.75 46.30 50.85 55.40 59.95
[11] 64.50 69.05 73.60 78.15 82.70 87.25 91.80 96.35 100.90 105.45

[1] "peak_sizes is: "
peak abs_size rel_size vals x y summit minor_variant_cov pair_cov
1 1 219787 0.44260407 93935 20 1 TRUE 0.4875 21.275
2 2 96007 0.19333759 16817 19 4 TRUE 0.4625 34.925
6 6 36636 0.07377708 3574 11 10 TRUE 0.2625 62.225
4 4 35319 0.07112492 4082 14 8 TRUE 0.3375 53.125
3 3 22937 0.04619022 5753 14 6 TRUE 0.3375 44.025
8 9 19703 0.03967763 2411 9 13 TRUE 0.2125 75.875
7 8 19426 0.03911981 2707 9 10 TRUE 0.2125 62.225
10 11 17660 0.03556347 2064 9 15 TRUE 0.2125 84.975
5 5 17647 0.03553729 4031 11 8 TRUE 0.2625 53.125
9 10 11455 0.02306792 2271 11 13 TRUE 0.2625 75.875
minor_variant_cov_rounded structure corrected_minor_variant_cov ploidy
1 0.50 AB 0.50 2
2 0.50 AAB 0.33 3
6 0.25 AAAABB 0.33 6
4 0.33 AAABB 0.40 5
3 0.33 AAAB 0.25 4
8 0.20 AAAAAAB 0.14 7
7 0.20 AAAAAB 0.17 6
10 0.20 AAAAAABB 0.25 8
5 0.25 AAAAB 0.20 5
9 0.25 AAAAABB 0.29 7
[1] "smudge_summary is: "
$n_subset_est
[1] 11.1

$n_peak_est
[1] 9.969065

$n
[1] 11.1

$peak_sizes
peak abs_size rel_size vals x y summit minor_variant_cov pair_cov
1 1 219787 0.44260407 93935 20 1 TRUE 0.4875 21.275
2 2 96007 0.19333759 16817 19 4 TRUE 0.4625 34.925
6 6 36636 0.07377708 3574 11 10 TRUE 0.2625 62.225
4 4 35319 0.07112492 4082 14 8 TRUE 0.3375 53.125
3 3 22937 0.04619022 5753 14 6 TRUE 0.3375 44.025
8 9 19703 0.03967763 2411 9 13 TRUE 0.2125 75.875
7 8 19426 0.03911981 2707 9 10 TRUE 0.2125 62.225
10 11 17660 0.03556347 2064 9 15 TRUE 0.2125 84.975
5 5 17647 0.03553729 4031 11 8 TRUE 0.2625 53.125
9 10 11455 0.02306792 2271 11 13 TRUE 0.2625 75.875

thanks much,
zhenzhen

**Comment by zhenzhenyang-psu** [comment]
Hi Kamil,
Based on my understanding, I added some numbers onto the smudgeplot. 
See below:
https://s3.wasabisys.com/aiden-zhenzhen/public/temp/temp_smudgeplot_Help/smudge_cutoff.png

If I wanted to use the 12 squares marked by the 2 long blue lines and 2 long red lines to represent the AB smudge, do you think it would be reasonable?

I see the "minor_variant_cov" and "pair_cov" from the $peak_sizes will return the ratio and total_cov of the peak smudges.  
peak_points <- peak_agregation(smudge_container)
 peak_sizes <- get_peak_summary(peak_points, smudge_container, 0.02)

I wonder what's your comment on the minor variant ratio if I want to differentiate heterozygous kmer pairs from paralogous kmer pairs?
zhenzhen

**Comment by KamilSJaron** [comment]
I would be honestly very hesitant to use this smudgeplot for anything. In that corner, it is really difficult to say if you have real genomic kmer pairs or if these are just error kmers paired with genomic ones. I would at least verify that the 1n estimate is similar for genomescope and smudgeplot.

What is a nice and not nice smudgeplot is difficult, so I compiled here several that are really nice, nice but a bit blended or not nice at all. Hope you will get the idea:

Look at the smudge pots like in #35, #36, #11, #42 - all these are clean pictures where you can really tell what is a smudge (it's not always obivous what is the ploidy, or how the smudge should be labeled, but you can certainly tell what is a smudge).

Then you have smudges like in #62, where smudgeplots are quite clear, but harder to separate due their overlap.

Contrasting to #37, #21 where the smudgeplots are blended and difficult for interpretation
