### ISSUE TITLE
extract counts for kmers of interest from dump or kmc out

### ISSUE THREAD

**Issue by zhenzhenyang-psu** [KamilSJaron/smudgeplot#60]
Hi Kamil or Timothy,
Sorry to bother. I would like to extract the times that a kmer of interest appears from the input fastq file.
I am asking because I didn't find that kmc has a way to do so. But I believe this must have been addressed somewhere in the smudge_pairs.cpp script, yet I am not familiar with C or C++.

I generated the following files using kmc:
kmcdb_L10_U71.dump
kmcdb_L10_U71.kmc_pre
kmcdb_L10_U71.kmc_suf

I tried to use grep from the dump file, as the dump file is as huge as 249G, it has taken me forever.
Is there an efficient way to extract a count from either one them given kmer sequence?
thanks a lot,
zhenzhen

**Comment by tbenavi1** [comment]
There is a faster way to do this. KMC has a c++ API to access the database and query for kmers. For example, see https://github.com/refresh-bio/KMC/issues/43. How many kmers would you like to query in this way? If just a handful, then you can use the CheckKmer function they suggest. If there are more, you can make a database of those kmers, then use kmc_tools to intersect the databases. Perhaps you can ask them prepare some code for you?

**Comment by zhenzhenyang-psu** [comment]
hi Timothy,
thanks very much for your solution. I will try out both. thanks for directing me to the right answer!
Zhenzhen

**Comment by KamilSJaron** [comment]
This seems resolved, closing now, feel free to reopen if something :-)
