### ISSUE TITLE
Bug in Smudgeplot example commands?

### ISSUE THREAD

**Issue by ms-gx** [KamilSJaron/smudgeplot#61]
If I am not mistaken, the following command is wrong in the README:
`smudge_pairs kmcdb_L$L\_U$U kmcdb_L$L\_U$U_coverages.tsv kmcdb_L$L\_U$U_pairs.tsv > kmcdb_L$L\_U$U_familysizes.tsv`

It should have an additional slash after `$U` for most of the filenames, otherwise it does not work properly I think.

So I think it should be:
`smudge_pairs kmcdb_L$L\_U$U kmcdb_L$L\_U$U\_coverages.tsv kmcdb_L$L\_U$U\_pairs.tsv > kmcdb_L$L\_U$U\_familysizes.tsv`

**Comment by KamilSJaron** [comment]
Ouch, I thought I have fixed that already - you are right. That line seems to be a bit iffy. I will put all varibable calls to "" in the README.

**Comment by KamilSJaron** [comment]
Thanks for pointing it out, I think it should be fixed now :-)

**Comment by ms-gx** [comment]
Thanks for your work! :)
