### ISSUE TITLE
Question on Smudgeplot result & general Smudgeplot question

### ISSUE THREAD

**Issue by ms-gx** [KamilSJaron/smudgeplot#62]
I would like to have some external assessment of my smudgeplot. I have used following commands to generate it (as suggested on Smudgeplot README)

```
ls *.fq.gz > FILES

kmc -k21 -t4 -m25 -ci1 -cs10000 @FILES kmcdb tmp

kmc_tools transform kmcdb histogram kmcdb_k21.hist -cx10000

L=$(smudgeplot.py cutoff kmcdb_k21.hist L)
U=$(smudgeplot.py cutoff kmcdb_k21.hist U)

kmc_tools transform kmcdb -ci"$L" -cx"$U" reduce kmcdb_L"$L"_U"$U"

smudge_pairs kmcdb_L"$L"_U"$U" kmcdb_L"$L"_U"$U"_coverages.tsv kmcdb_L"$L"_U"$U"_pairs.tsv > kmcdb_L"$L"_U"$U"_familysizes.tsv

smudgeplot.py plot kmcdb_L"$L"_U"$U"_coverages.tsv
```
Whereas `L=12` and `U=430`.

and it looks like this:

![smudgeplot_smudgeplot_log10](https://user-images.githubusercontent.com/45788632/87071864-280bf800-c21b-11ea-9ffd-a07b77c55ae5.png)

Now, I know already that the genome is supposed to be tetraploid from literature (karyotype). This is in line with the Smudgeplot result. However, apart from the karyotype there there is not much more information on the genome structure.

My questions:
1. It looks to me that the Smudgeplot indicates that the tetraploid genome is rather allotetraploid than autotetraploid (as shown for example here in Figure 2: https://www.nature.com/articles/s41467-020-14998-3)
OR
2. the duplication is autotetraploid (with duplication of all chromosomes as one single event) and rather recent (since most pairs are "AB" or "AABB"). Does this make sense?
3. The peak at "AAAABB" seems more of an artefact to me and not so much a "true" smudge?

The corresponding GenomeScope2 plots are here:
- With analysis for 4n: http://genomescope.org/genomescope2.0/analysis.php?code=h4gMKlFJvOwuHm3gOJzJ
- With analysis for 2n: http://genomescope.org/genomescope2.0/analysis.php?code=5y4SQw0TTNzI94JjYNI0

What is your take on the genome structure for this?

Another general question: I do not understand the bimodal distribution on the total coverage if we assume that all chromosomes are tetraploid. How does this happen?
EDIT: could this be a sign of diploidization?

**Comment by KamilSJaron** [comment]
Hi Michael, this is great. And got to say a very thorough question. 

1./2. Your genome is quite convincingly tetraploid of AABB type. I don't think we know enough about post-autotetraploidy evoluiton to conclusively say it's an allotetraploid solely on AABB structure, but it's certainly an indication. However, if it's an autotetraploid, it must be really really old, as the divergence of AA <-> BB is substantial and much higher than what heterozygosity could be (looking at the genomescope, but also you see how crazylot of kmer pairs you found).

3. Nah, the peak is real. It's not big but it's real. These are probably duplications in only AA or BB (creating AAAABB topologies). One of the surprises we faced in smudgeplot development was how much paralog signal we are picking up. In diploid species without much heterozygosity, we sometimes get so much paralog signal that it looks like tetraploid species too. However, I would not overinterpret the existence of that smudge. It merely shows that paralogs exist in non-trivial number, but it's not a proper quantification of their frequency. It's something that can nudge subsequential exploration of paralogs in your genome.

Does it answer your questions?

**Comment by ms-gx** [comment]
Hi Kamil

Thanks for your excellent answers.

I still have some questions:
1) So you would say that you see more divergence than "normal" heterozygosity? Thing is that this is in line with the underlying ONT assembly I have for this species which apparently does not collapse a lot of homologous chromosome regions. Also in BUSCO analysis I see lots of genes which are duplicates.
2) Could we say that is looks like in this genome the duplicated chromosomes really evolved heavily and kinda got very different in their characteristics from the initial homologue counterpart? Or it was really an allotetraploid, which explains that.
3) I still do not really understand the peak at "AB". What are possible explanations for this?

Best
Michael

**Comment by KamilSJaron** [comment]
1. "homologous chromosome regions" is a bit confusing:
  - I would expect A <-> A;  B <-> B  homologs to be moreless collapsed (this is heterozygosity sensu stricto and it's not exceptionally high)
  - while I would NOT expect AA <-> BB homologs (ohno/homoeologs) to be collapsed at all as their divergence is estimated to be over 11% (heterozygosity of a classical diploid sexual species is ~0.3 - 2%). That is what can generate high % of BUSCO duplicates.

2. One or the order, that's really impossible to say without more clues. Allo- would be an easy explanation of the two diverged genome copies, but the only really conclusive way to confirm allopolyploidy is to identify at least one of the parental lineages.

3. AB peak is made of heteoryzgosity sensu stricto alleles of AA' --, -- BB' type. Where - denotes either deletion or alleles that are diverged (A <-> B) by more than one SNP (smudgeplot isolates all the kmer pairs that are one SNP from each other and form a unique pair)

**Comment by ms-gx** [comment]
Makes sense... Thanks much! Closing the issue for now.

**Comment by Tiramisu023** [comment]
Hi,
Could you please share how to install **smudge_pairs** ? I also want to use this tool because **smudgeplot.py hetkmers** is too slow for my data.
> smudge_pairs kmcdb_L"$L"_U"$U" kmcdb_L"$L"_U"$U"_coverages.tsv kmcdb_L"$L"_U"$U"_pairs.tsv > kmcdb_L"$L"_U"$U"_familysizes.tsv
Thanks!

**Comment by ms-gx** [comment]
It is available here:
https://github.com/tbenavi1/KMC

This is also stated on:
https://github.com/KamilSJaron/smudgeplot
--> "smudge_pairs is available at tbenavi1/KMC. Specifically, after compiling this version of KMC, smudge_pairs will be in the bin directory."

All the best!

**Comment by KamilSJaron** [comment]
Thanks @ms-gx, appreciated :-)

**Comment by Tiramisu023** [comment]
> It is available here:
> https://github.com/tbenavi1/KMC
> 
> This is also stated on:
> https://github.com/KamilSJaron/smudgeplot
> --> "smudge_pairs is available at tbenavi1/KMC. Specifically, after compiling this version of KMC, smudge_pairs will be in the bin directory."
> 
> All the best!

Thank you.  I just thought it was the same software with `[refresh-bio/KMC](https://github.com/refresh-bio/KMC)` at first.  Therefore I only compiled  `refresh-bio/KMC`, and found no `smudge_pairs`.

I will try `tbenavi1/KMC`. Thanks you so much.

**Comment by KamilSJaron** [comment]
Yeah, it's a fork. We should probably are some point package it a bit better.
