### ISSUE TITLE
No package called smudgeplot

### ISSUE THREAD

**Issue by heatherturtle** [KamilSJaron/smudgeplot#63]
Hello,

I installed smudgeplot0.2.3 using conda and I am getting the following error.  I have tried manually installing smudgeplot in R, but for just about all versions of R, it says that there is no package named "smudgeplot".  
<img width="970" alt="Screen Shot 2020-07-13 at 4 48 07 PM" src="https://user-images.githubusercontent.com/53024233/87357838-5266f980-c52a-11ea-8890-7564d4078d9c.png">

**Comment by KamilSJaron** [comment]
Hi there,

Conda installs R package a moves 2 scipts in it's directories. The thw scripts got installed as they should, but it seems that the R package got not. I have no idea why is that, but I am quite sure that if you make a fresh conda env, it will work as expected.d

**Comment by KamilSJaron** [comment]
I am closing it for now, if there is still a problem, don't hesitate to reopen the issue.
