### ISSUE TITLE
Extraction of smudges using exact boundaries

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/smudgeplot#67]
> Merged from #59 by @zhenzhenyang-psu:

I have spent more time on studying the smudeplot code and have found out the "peak" column from "peak_points"  data matrix recorded which bins share the same structute(smudge).  I also think it is not a bad idea to integrate it into smudge plot.
ideally this can be written to an output file and also line up the boundaries of bins that have the same smudge structure. Unfortunately I am not quite familiar with R, so some help or discussions are appreciated. Do you have interest in this?

**Comment by KamilSJaron** [comment]
I think it would be really useful to extract kmers by boundaries of the smudges. I actually did want to implement it, but I never got around to actually do so.

I guess the easiest would be to export the data structure with bins assigned to smudges (I don't recall if I called it "peak_points", but it could be, during the development I called smudges peaks) and then use that.

I think it would be good to also give the kmers a credibility measure. Perhaps distance to the smudge peak could be one. There could probably be a parametric one too, if we actually start fitting there some distributions (having likelihood would be cooool). This is not essential, but I think it's a good consideration here.

If you lead, I am happy to help as much as I can.

**Comment by zhenzhenyang-psu** [comment]
sounds good. it would be good to assign a confidence score to each bin.
Let me give it some thought and see how to implement it.
I guess the first thing to do is to for instance, if there are 3 structures, name them 1, 2,3 and label corresponding bins with these numbers. what are your opinions on this? once we label the structures, we can later think about the confidence score sort of thing.
zhenzhen
________________________________
