### ISSUE TITLE
Smudgeplot  needs too huge memory 

### ISSUE THREAD

**Issue by Cucuapple** [KamilSJaron/smudgeplot#69]
Hi Kamil, 
 Thanks for such an excellent software. 
 However, there was a trouble when I used Smudgeplot to analyze the haplotype of a polyploid: The Smudgeplot needs too huge memory,  even to 4Tb.
     
Here is my command:  

     jellyfish dump -c -L 5 -U 300 tttt.counts.jf -o AAAA    (This step is finished. "tttt.counts.jf" is ~300Gb and "AAAA" is ~120Gb)
     smudgeplot.py hetkmers -o kmer_pairs AAAA   (This step is not finished because it needs over 4Tb memory).
     
So, the question is whether I didn't use the software correcetly, or it indeed need a huge memory. 

Best wishes

**Comment by KamilSJaron** [comment]
Hi Cucuapple,

Look at the current recommendation regarding [usage](https://github.com/KamilSJaron/smudgeplot#usage). The python script you use is easier to operate, but the algorithm to find all the kmer pairs is unfortunatelly not very efficient. For bigger genomes (as yours unadoubtably is) we recommend to use an algorithm implemented in C++: https://github.com/tbenavi1/KMC

This version consumes significantly less memory and runs faster.

Hope this helps.

**Comment by Cucuapple** [comment]
Hi Kamil，

     Thanks for your suggestion.
     I will have a try :)

Best wishes

**Comment by KamilSJaron** [comment]
Sure, I will close the issue for now. In the case you would have still problems, feel free to reopen.
