### ISSUE TITLE
explore other options how to identify heterozygous kmers

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/smudgeplot#7]
The smudgeplot is now limited for heterozygosity only to certain extend (we extract kemrs that are 1SNP from each other). If the divergence of haplotypes is too great, we are unable to /identify any (the case of Rotifer).

We might want to explore a way how to identify heterozygous kmers with indels, or of greater divergence than 1 SNP (parameter?).

I wonder if blast is a possibility or not. One could define a similarity treshold and uniqueness threshold (if simularity would be from 0 - 100, you could stay that you accept all pairs with score >90 where the third closest kmers is < 50 or something like that). Or some sort of blast-like approach that would be bit more sloppy on the alignment part (Minimap?).

**Comment by KamilSJaron** [comment]
Drafted in c03a52ba9581e2e9c4725284b24cb631f12c6367

**Comment by kiraza-lab** [comment]
Dear KamilSJaron,
Am I right that in case of high heterozygosity (for instance, intensive genome reshuffling after allotetraploidization accompanied by TE activation) smudgeplot can give incorrect prediction regarding to the genome  ploidy level? How to present data obtained with GenomeScope2.0 in this case? And another question is about the coverage level of such genome (10x is too low or enough for estimation of main genome parameters?)
Sincerely,
Kira.

**Comment by KamilSJaron** [comment]
Hi Kira,

smudgeplot is a visualization technique that uses closely related kmer pairs as a proxy for heterozygous and potentially paralogous loci. For different biological cases the interpretations can be more or less tricky (which is also the reason why we were thinking of using different ways to define kmer pairs). If you have some strange smudgeplots, you can open a new issue and post them there. I can take a look.

**Comment by KamilSJaron** [comment]
We are probably quite happy about this in the end
