### ISSUE TITLE
genomesize and ploidy in plants interpretation

### ISSUE THREAD

**Issue by LluisGarciaMir** [KamilSJaron/smudgeplot#73]
I have troubles understanding my smudgeplot. I have used the following commands to generate different smudges, one plot letting the program use the infered 1n haploid coverage, and others using GenomeScope2 kmer coverage estimate for the three possible ploidies, since the species is probably an autopolyploid, but ploidy level is unclear. Histograms were computed with KMC3.

```
smudgeplot_plot.R plot -i kmer_pairs_L10_U250_coverages_2.tsv -o N_pho_L10_U250_k21 -t "N.pho k21" -k 19
smudgeplot_plot.R plot -i kmer_pairs_L10_U250_coverages_2.tsv -o N_pho_L10_U250_k21_1n_GS2_p2_p4 -t "N.pho k21" -k 19 -n 46
smudgeplot_plot.R plot -i kmer_pairs_L10_U250_coverages_2.tsv -o N_pho_L10_U250_k21_1n_GS2_p2_p4 -t "N.pho k21" -k 19 -n 22
```

and it look like this:

KMC histogram (limits used in further smudgeplots):

![KMC_NAV_k21_histogram](https://user-images.githubusercontent.com/58775083/91705041-b8601c80-eb7c-11ea-93d6-37f38a4ce28c.png)

smudgeplot with 1n coverage infered from data

![NPHO_k21_L10_U250_smudgeplot_log10](https://user-images.githubusercontent.com/58775083/91702945-bc3e6f80-eb79-11ea-902d-fb8b446e9bd1.png)

smudgeplot with 1n coverage = 43 (haploid kmer coverage by GenomeScope2 when ploidy is 2 or 6)

![NPHO_k21_L10_U250_n_GS2_p2_p6_smudgeplot_log10](https://user-images.githubusercontent.com/58775083/91705210-f52c1380-eb7c-11ea-9a11-ad9535dc259f.png)

GenomeScope2 results for p2 and p6

![GS2 0_KMC3_N phoenicea_k21_p2_transformed_linear_plot](https://user-images.githubusercontent.com/58775083/91703433-759d4500-eb7a-11ea-8e73-1aee00901642.png)
![GS2 0_KMC3_N phoenicea_k21_p6_transformed_linear_plot](https://user-images.githubusercontent.com/58775083/91703462-8352ca80-eb7a-11ea-905d-bb2058344a4a.png)

smudgeplot with 1n coverage = 21 ( haploid kmer coverage by GenomeScope2 when ploidy level is 4)

![NPHO_k21_L10_U250_n_GS2_p4_smudgeplot_log10](https://user-images.githubusercontent.com/58775083/91703133-032c6500-eb7a-11ea-9d05-44977034f449.png)
![GS2 0_KMC3_N phoenicea_k21_p4_transformed_linear_plot](https://user-images.githubusercontent.com/58775083/91705141-dcbbf900-eb7c-11ea-9263-41f25137587d.png)

Now, I know already genome size by flow citometry which is 3.8-4.0 Gb, 
and by karyiotype studies chromosome number (2n) is 44, probably an autohexaploid species with chromosome base number 7, although not clear if tetraploid with base number 11. In addition, it is not really clear if chromosome number is 44, there are observations of 42 chromosomes, so it could be genomic rearrangements (so results should be misleaded?)

This does not make sense: according to previous chromosome number studies, the predicted 10-ploid doesn't match to possible ploidies.  On the other hand, Smudgeplot reports a tetraploid when the haploid coverage recovered from GenomeScope2 is calculated with diploid or hexaploid levels, which are identical.  In these cases, genome size estimates seem to be less than half the total size (1.7 Gb vs 3.8Gb)

How should I understand my smudgeplots? Thank you very much for the help

**Comment by KamilSJaron** [comment]
Hi Lluis,

I will have a few comments. In general, smudgeplot is mainly a visualization tool, the annotations are sometimes wrong (and that's certainly the case in the one you showed). The background image (the smudges) are a pure representation of your sequencing data.

The problem in your case is that L=10 is too small and too many sequencing errors got in the analysis. The haploid kmer coverage is about 42x (the histogram is clearly showing that the smallest peak is ~42x), hence you can pick your L = 30 and you will be fine (sure, you will lose a few haploid kmers that happen to have smaller coverage by chance, but the signal will get must clearer). In fact if you gave smudgeplot the coverage prior (-n 42), it produced a smudgeplot I would expect. I think that if kind of what you would get if you increase L. Looks quite tetraploidy to me :-).

About the mismatched genome sizes. Note that the kmer historgram you used in your genomescope analysis is turnicated from the right side (you have no kmers with more than 250x), which will certainly affect your genome size estimate. This [this](https://kamilsjaron.github.io/peculiar-genomic-observations/biological/2020/01/crayfish.html) blogpost I show how much it can change the estimate in crayfish. I would recommend to use a really large number if you think your genome is repetitive (1e7 or even more)

**Comment by LluisGarciaMir** [comment]
Dear Kamil, 

Thanks for your comments, they’ve been helpful! 

After lengthening the histogram to -cs 5e8 (as in the crayfish example) a big difference in counts in the kmers tail is appreciated. There are kmers now until cvg ~400M, what turns out to be differences in genome size estimates:

| flow citometry | ploidy | genome size <br> truncated histo | genome size <br> full histo |
|----------------|--------|-----------------------------|------------------------|
| 3.8-4.0       | 2      | 1.74                        | 3.81                   |
|                | 4      | 3.47                        | 1.87                   |
|                | 6      | 1.74                        | 1.87                   | 

It is interesting how the best estimates are flipped between p2 and p4 depending on the presence of repetitive kmers in the distribution. Now, looking at the results of Genomescope2 alone it would seem that this species is likely a diploid, but probably this observation is due to the way of computing genome size according to a certain ploidy level by GS2. 

For my understanding, would be GS2 expecting more kmers in the repetitive tail (let’s say, 1 or 2 times more) to make a better estimate of size with ploidy 4? In that case results p2-p4 would be reflecting the effect of diploidization, but leaving me to wonder why the estimate with the truncated histogram and ploidy 4 is close to the actual size.

I am waiting to have the results of Smudgeplot and will let you know.

**Comment by KamilSJaron** [comment]
Hi Lluis, the genomescope models you posted do not seem to match the numers you specified in the table.

The total genome size (what you measure by FC, but assuming that the number was not divided by 2 as sometimes people do) is ploidy * haploid genome size. So I guess the truncated "genome sizes" are
```
2 * 855M = 1.6someting Gbp
4 * 204M = 0.808 Gbp (which is exactly half than the other two)
6 * 285M = 1.6someting Gbp
```

How did you get the numbers in the table you showed? Would you like to paste here the tetraploid GenomesScope model on the non-truncated histogram?

**Comment by LluisGarciaMir** [comment]
Hi, 

FC measures are of 2C values, total genome size of somatic leaf cells.

I calculated total genome sizes as you indicated yesterday, but there was a mistake in p4 for the truncated histo 
thank you for correction.

Here are the models with full histograms

![GS2_KMC3_N phoenicea_k21_p2_full_transformed_linear_plot](https://user-images.githubusercontent.com/58775083/92099242-94017b80-edda-11ea-839e-0f10cc74a29e.png)

![GS2_KMC3_N phoenicea_k21_p4_full_transformed_linear_plot](https://user-images.githubusercontent.com/58775083/92099283-9e237a00-edda-11ea-822b-a08aa82ea713.png)

![GS2_KMC3_N phoenicea_k21_p6_full_transformed_linear_plot](https://user-images.githubusercontent.com/58775083/92099316-a7144b80-edda-11ea-9604-73b28dc9552e.png)


| flow citometry | ploidy | genome size truncated histo | genome size full histo |
|----------------|--------|-----------------------------|------------------------|
| 3.8-4.0        | 2      | 1.74                        | 3.81                   |
|                | 4      | 0.82                        | 1.87                   |
|                | 6      | 1.74                        | 1.87                   |

**Comment by KamilSJaron** [comment]
Ah, excellent. We sorted that one out.

So, if you look at the three models you posted, the real problem is that tetraploid and hexaploid model fit a wrong (twice bigger) haploid coverage. You know that the 1n coverage is 42x ( it's quite suggestive just by looking at the histogram and also supported by smudgeplot), so it's time to tell it to GenomeScope. You can specify a coverage prior, if you do so, I am 100% sure you will get your expected genome size :-)

**Comment by LluisGarciaMir** [comment]
Hi Kamil, 

Rerunning GS2 with a proper -l prior gives results that are within FC. In fact for genome size all results 
are identical to FC sow now I see the synergic effect of combining both programs using adequate parameters. Understanding the influence of k-coverage is key and I am really glad of having libraries with a sufficient cvg for obtaining results.

| flow citometry | ploidy | genome size truncated histo | genome size full histo |
|----------------|--------|-----------------------------|------------------------|
| 3.8-4.0        | 2      | 1.74                        | 3.81                   |
|                | 4      | 0.82                        | 3.81                   |
|                | 6      | 1.74                        | 3.81                   |

About Smudgeplot, it reports a tetraploid genome as previously seen with the truncated histogram :)
With L=25 and -n 43 smudgeplot warns that there are heterozygous pairs missing until L=20, but anyway this result seems pretty acceptable. However, taking together the karyotypes and the AAAABB = 0.12 smudge, do you think there is a probability of a truly hexaploid?

![NAV_k21_full_L25_U5400_n_43_smudgeplot_log10](https://user-images.githubusercontent.com/58775083/92383522-c7137a00-f10e-11ea-9d74-28195c391570.png)


Now I am extending the analysis to two related species and I expect to get similar nice results.

Overall the utility of these tools is excellent. Thanks a lot for them and for the help!

**Comment by KamilSJaron** [comment]
Cool, glad the analysis worked out for you :-).

Re hexaploid: Nah, at least nah based only on the smudgeplot. Genomes are full paralogs, you always find some kmer pairs with "higher plodies". 12% is quite a lot, but still within what could be still just due to paralog pairs. However, you are right that in tetraploid genome you would naturally expect much more octoploid paralogs (which are simply duplications) than hexaploid (duplication + indel in 2 out of 8 loci).

Your data looks great, perhaps you will figure out more by digging into the assembly (now that you know what to expect).

Can I close the issue now?

K

**Comment by LluisGarciaMir** [comment]
Yes!
