### ISSUE TITLE
trying to find an appropriate lower bound for Smudgeplot in order to infer ploidy

### ISSUE THREAD

**Issue by tylerdodgeball** [KamilSJaron/smudgeplot#75]
I used nQuire with a reference genome to predict that my genome is tetraploid, and an existing publication based on nuclear sizes also suggests that this genome is tetraploid.  I wanted to use Smudgeplot because the approach is orthogonal, and also, because it permits detection of higher ploidies, ie beyond tetraploid.

For my genome, Smudgeplot predicts different ploidies, from diploid to triploid to tetraploid to octaploid when I choose different lower bounds ("$L") in the tutorial.

My genomescope 2.0 plot looks like this (the "error" section of the plot is pretty wide).  Can you tell me what value I should choose for the lower bound?

-TylerDodgeball

![image](https://user-images.githubusercontent.com/67129008/97241223-b053e000-17ad-11eb-9d6d-06d7c12605bf.png)

**Comment by KamilSJaron** [comment]
Hi Tayler Dodgeball, a few things when I look at this kmer spectra

1. The model is completely off (the black line does not fir the blue histogram). You could try to fit there tetraploid model instead.
2. I am not sure what is your genome in the histogram, there a peak around 50x, then 1300x and 2600x. L should be chosen so it separates the target genomic kmers and the errors (or contaminations). The 1300x is the real genomic peak, you can choose L=500 and it's going to be still safe. If you want to work also with the coverage peak around 50x we would need to zoom in to figure things out.
3. What is your approximate covrage? (you can get the idea from mapped reads, or from dividing the sequencing library size by expected gneome size). Then you can pick L that is a bit bellow your expected haploid covrage.

Good luck

**Comment by tylerdodgeball** [comment]
The nuclear genome is at around 1500X coverage for (non-deduplicated reads).  The 50X peak is likely contaminants such as bacteria.  The 2600X coverage I'm not sure, but may be plastids, which I'm not trying to work with.  If the kmer peaks correspond to these same coverage levels, then it should be easy to set the L value to 500 and we're good I think.  I did try that previously and it gave the expected results.

**Comment by KamilSJaron** [comment]
Cool, so everything is alright? Can I close the issue?

**Comment by tylerdodgeball** [comment]
Yes, thank you for your help!
