### ISSUE TITLE
Trouble identifying haploid/deploid genome

### ISSUE THREAD

**Issue by RaulGoch** [KamilSJaron/smudgeplot#76]
Hi Kamil,

I have trouble determining the ploidy of one of my genomes. It is thought to be haploid. I used the following command to generate it:

```
smudgeplot plot -i kmer_pairs_coverages.tsv -o my_sample
```

and it looks like this:

![smudgeplot_smudgeplot_log10](https://user-images.githubusercontent.com/32655636/99312508-22a76580-282c-11eb-9eb2-ed337b186a39.png)

I am aware that the smudgeplot can't predict haploid genomes, so I ran GenomeScope 2.0 with ploidy = 1:

![04-503SCI 03_GenomeScope2 0_p1](https://user-images.githubusercontent.com/32655636/99312855-a8c3ac00-282c-11eb-8766-27aee4fe89de.png)
GenomeScope version 2.0
input file = user_uploads/hugJdQqni0JySgNIGsXd
output directory = user_data/hugJdQqni0JySgNIGsXd
p = 1
k = 21
max_kmercov = 1000000

property                      min               max               
Homozygous (a)                100%              100%              
Genome Haploid Length         1,046,403,382 bp  1,049,047,530 bp  
Genome Repeat Length          439,835,825 bp    440,947,243 bp    
Genome Unique Length          606,567,557 bp    608,100,288 bp    
Model Fit                     58.2575%          94.0288%          
Read Error Rate               0.218439%         0.218439%  

and ploidy = 2:

![04-503SCI 03_GenomeScope2 0_p2](https://user-images.githubusercontent.com/32655636/99312950-c729a780-282c-11eb-9876-ba68f970144c.png)
GenomeScope version 2.0
input file = user_uploads/VZhkGLVdMgxOnbrU6SNG
output directory = user_data/VZhkGLVdMgxOnbrU6SNG
p = 2
k = 21
max_kmercov = 1000000

property                      min               max               
Homozygous (aa)               99.7629%          99.7989%          
Heterozygous (ab)             0.201105%         0.237079%         
Genome Haploid Length         1,074,040,019 bp  1,076,438,486 bp  
Genome Repeat Length          449,193,325 bp    450,196,430 bp    
Genome Unique Length          624,846,694 bp    626,242,056 bp    
Model Fit                     60.121%           94.3922%          
Read Error Rate               0.08393%          0.08393%  

there doesn't seem to be much difference between the fitted models. However, the estimated repeat sequence is shorter than the unique sequence. Am I correct to assume that this probably means that the genome is haploid but highly repetitive?

**Comment by KamilSJaron** [comment]
Hi RaulGoch,

you are right - smudgeplot can detect ploidy only if there are heterozygous loci in there. Hence, detecting ploidy in a haploid organism won't really work. The smudgeplot still shows you a real signal, but of paralogs within the genome. 

Your two models are kind of the same, the second is reporting some heterozygosity, but that's just a bad fit. If that heterozygosity would be real, smudgeplot would pick on that signal. So I agree the genome is haploid.

Every genome is repetitive to certain extend and it's I would say among intermediate values (this is actually what I would call "alright repetitive"). But yes, you will probably be able to annotate a fair share of TEs in this one.

Seems you got everything right :-), can I close the issue?

**Comment by RaulGoch** [comment]
Hi Kamil,

thanks for clarifying! Yes, we can close the issue now!

**Comment by KamilSJaron** [comment]
Happy to help
