### ISSUE TITLE
The speed about the smudgeplot.py

### ISSUE THREAD

**Issue by Slowlywalkingdownthehall** [KamilSJaron/smudgeplot#78]
The count results of `jellyfihs count` is about 7GB. And my server doesn't have the SLURM. How to make this step faster? 
`jellyfish dump -c -L $L -U $U 17mer_out | smudgeplot.py hetkmers -o kmer_pairs`

**Comment by KamilSJaron** [comment]
That's a lot of data. I recommend exactly what is the in the readme file, `smudge_pairs` algorithm is much faster than the python script.

e.g.
```
kmc_tools transform kmcdb -ci"$L" -cx"$U" reduce kmcdb_L"$L"_U"$U"
smudge_pairs kmcdb_L"$L"_U"$U" kmcdb_L"$L"_U"$U"_coverages.tsv kmcdb_L"$L"_U"$U"_pairs.tsv > kmcdb_L"$L"_U"$U"_familysizes.tsv
```
