### ISSUE TITLE
new smudgeplot mascot?

### ISSUE THREAD

**Issue by KamilSJaron** [KamilSJaron/smudgeplot#81]
![WhatsApp Image 2020-12-18 at 1 24 04 PM](https://user-images.githubusercontent.com/8181573/102619733-d0ac7500-4134-11eb-9d6c-92542624f8c0.jpeg)

**Comment by sivico26** [comment]
I strongly support this initiative

**Comment by KamilSJaron** [comment]
Then se should give a big shout out to @MooHoll for taking such a good are of Smudge.
