### ISSUE TITLE
Thread occupy

### ISSUE THREAD

**Issue by WangYuan20190517** [KamilSJaron/smudgeplot#83]
Hi,

When I use **jellyfish dump -c -L $L -U $U $baas | $dir/smudgeplot.py hetkmers -o kmer_pairs**  command , it occupies all my threads. And it has been running for more than two hours.  My genome is about 0.8GB. Is this normal? 

Thanks

**Comment by KamilSJaron** [comment]
Hi, more than 2 hours is normal, all threads is not (unless you have just 2 threads). The current version of smudgeplot does not support multithreading, but I would not really expect jellyfish dump to go rogue either. Have you considered using the `smudge_pairs` program instead? It's a more efficient implementation of the same algorithm (it's the first suggestion in the Usage section of the README file).

**Comment by WangYuan20190517** [comment]
Thank you! I use 22 thread before, so may be the filtering problem. I will use the smudge_pairs then. But the install of smudge_pairs is diffcult. https://github.com/refresh-bio/KMC/issues/166

**Comment by KamilSJaron** [comment]
`smudge_pairs` is a program created in a fork of KMC at the following url://github.com/tbenavi1/KMC

Installing is almost the same as the original KMC program, and it's described in the README of the fork. I hope it will be work for you.

**Comment by KamilSJaron** [comment]
I will close this issue for now, feel free to reopen it or submit a new one if anything
