### ISSUE TITLE
Long run time of step 'extract kmers in the coverage range'

### ISSUE THREAD

**Issue by Axolotl233** [KamilSJaron/smudgeplot#86]
Hi，

When I run smudgeplot pipeline follow the usage you provided with my data, i found program seem stop on 'extract kmers in the coverage range'. it has no screen update and no file create, just with standard screen out “in1: 0%” after I submit task.

my command line is ```kmc_tools transform kmcdb -ci"$L" -cx"$U" reduce kmcdb_L"$L"_U"$U"```

please kindly tell me if it is normally(this step take long time) or something wrong with my command or data?

**Comment by Axolotl233** [comment]
I simply sovled it by using another PC,  maybe `kmc_tool` is not compatible with my machine.

**Comment by KamilSJaron** [comment]
Indeed, It should not take much time, glad it got resolved :-)
