### ISSUE TITLE
diffcult to interpret result plot with tetraploid dataset

### ISSUE THREAD

**Issue by Axolotl233** [KamilSJaron/smudgeplot#87]
I tested Smudgeplot with my tetraploid species, but I have troubles understanding output plot. 
I ran Smudgeplot with follwing commands
```
kmc -k21 -t30 -m128 -ci1 -cs10000 @read.lst kmcdb ./tmp
kmc_tools transform kmcdb histogram kmcdb_k21.hist -cx10000
L=$(smudgeplot.py cutoff kmcdb_k21.hist L)
U=$(smudgeplot.py cutoff kmcdb_k21.hist U)
kmc_tools transform kmcdb -ci"$L" -cx"$U" reduce kmcdb_L"$L"_U"$U"
smudge_pairs kmcdb_L"$L"_U"$U" kmcdb_L"$L"_U"$U"_coverages.tsv kmcdb_L"$L"_U"$U"_pairs.tsv > kmcdb_L"$L"_U"$U"_familysizes.tsv
smudgeplot.py plot kmcdb_L"$L"_U"$U"_coverages.tsv
```
`L` and `U` equal 12 and 1300, respectively. Thre result look like this(tetraploid_1.png).
![tetraploid_1](https://user-images.githubusercontent.com/45548556/112605180-fc38ad00-8e51-11eb-9a49-d61c3222a3d2.png)

I aslo tested Smudgeplot with another tetraploid dataset form publication,  DOI:https://doi.org/10.1016/j.molp.2020.07.003 (a autopolyploid)
The results seem difficult to interpret too(tetraploid_2)
![tetraploid_2](https://user-images.githubusercontent.com/45548556/112606526-600fa580-8e53-11eb-8226-ce6f6c54ab36.png)

How should I understand my smudgeplots?

**Comment by KamilSJaron** [comment]
Hi @Axolotl233, sorry for such a delay.

It's hard to say what's going on with your data. The first smudgeplot actually looks quite alright, but very much like a diploid without any sign of a problem. Does the 1n estimate correspond to what do you see in the kmer histogram?

The second dataset looks like a messed smudgeplot of tetraploid data. I suspect the coverage is not the greatest, but with a more careful choice of L you might be able to get it annotated well. See for example the problems we had when generating a smudgeplot for a polyploid yeast (Check [this tutorial](https://github.com/KamilSJaron/smudgeplot/wiki/tutorial-saccharomyces)). 

Without knowing also the kmer histograms is hard to say more.

**Comment by Axolotl233** [comment]
Hi.
for two datasets, i draw a kmer histogram and upload them in appendix. the `histo` files are same with input of smudgeplot. The parament  `ploid` is 2 and 4 for two dataset respectively.
1:
![qimu](https://user-images.githubusercontent.com/45548556/114704465-37dfdc00-9d59-11eb-904d-87887538b67c.png)
2:
![muxu](https://user-images.githubusercontent.com/45548556/114704501-40d0ad80-9d59-11eb-8860-f65ff94ac226.png)

i I have not change parameter L of second dataset yet, i doubt datasize of it is insufficient to estimate ploid.

**Comment by KamilSJaron** [comment]
So the first genome appears to have only two peaks in the histogram, one around 30x and one in 60x, this kind of corresponds to what smudgeplot shows, with estimated 1n coverage. So it seems that most of the kmer pairs are formed from two kmers of the 1n peak. Looks like a diploid.

The second case is sneakier, it almost look like the histogram and the smudgeplot are not the same data (I don't see which peaks are pairing to give arise that funky smudgeplot). 

However, like it or not, both those datasets fall quite short on coverage and that's what generates a lot of interpretational uncertainity. Especially the second one has quite messed error and genome kmers together.
