### ISSUE TITLE
Ploidy estimation in a very low heterozygosity genome

### ISSUE THREAD

**Issue by OliverPStuart** [KamilSJaron/smudgeplot#89]
Hi Kamil,

I have some questions about the interpretation of combined Smudgeplot+GenomeScope2.0 results, with respect to what I already know about the genome of my species. I'm using OmniC short-read data for this analysis. I know that Hi-C is not recommended for this approach, but I am hoping that OmniC (which I have checked has quite even, but low, alignment coverage) will be okay. The genome is (probably) highly repetitive and mostly homozygous, so I am wary of strange artefacts.

Depending on the k-mer size, GenomeScope2.0 estimates one of the following:
- at k=21, a genome of 1.8 Gbp with k-mer coverage of 33 and heterozygosity =~ 10%
- at k>21, a genome of 3.7 Gbp with k-mer coverage of 18 and heterozygosity << 0.1 %

Of these two, I have more confidence in the latter, as this matches what we know about the species' history and genome size/structure from our scaffolded genome assembly and karyotype. A few features of the assembly match the karyotype so I am quite confident in it.

However, when using the GenomeScope2.0 haploid k-mer coverage of 18 for Smudgeplot (following the suggestions in the Saccharomyces tutorial), the guess is tetraploid:

![kmer23_omniC_12_510_smudgeplot_n18](https://user-images.githubusercontent.com/50858585/124404529-a774ce80-dd7e-11eb-8a20-4581356364f1.png)

When I let Smudgeplot estimate the haploid coverage on its own, I get the diploid answer I expect:

![kmer23_omniC_12_510_smudgeplot](https://user-images.githubusercontent.com/50858585/124404534-aa6fbf00-dd7e-11eb-9069-be675928b939.png)

Is this what I would expect to see if the genome is almost entirely homozygous?

**Comment by KamilSJaron** [comment]
Hi Olivier,

first, the two estimates of genome size / heterozygosity have more to do with the fit of the haploid coverage. In some edge cases it's really hard to say if it's a homozygous genome or twice a smaller extremly heterozygous genome. Changing k probably changes the fits a tiny bit in the favour of the other model, but if you would specify priors on the 1n coverage, I bet it would converege to similar genome sizes regardless on the chosen k. So let's say homozygous genome it is.

If it is a homozygous genome and you are positive on the haploid coverage, you should not be worried that you see nearly exclusively the paralog smudge. For genomes of this size, it's very much possible that high homozygosity can lead to the smudgeplot you have observed.

**Comment by KamilSJaron** [comment]
As usual - I am closing presumably resolved issues, but if anything don't hesitate to reopen
