### ISSUE TITLE
Mention conda package in README.md

### ISSUE THREAD

**Issue by hannesbecher** [KamilSJaron/smudgeplot#91]
Just a suggestion. Hope this is not annoying. The repo's README (installation section) could mention the fact that there is a conda package: https://anaconda.org/bioconda/smudgeplot

**Comment by mschatz** [comment]
Thanks! The conda package is a very recent addition and you are right we
should update the readme to highlight this option

Thanks!

Mike

**Comment by KamilSJaron** [comment]
Sound, I think it's reasonable to propose conda as the default and offer other options in the wiki alongside the rest of the documentation. Adjusted in f2d361d5e3fb7de9318edd5e8dee8ef619392b46. Thanks for the suggestion!
